import { Headline } from "@/types";

export const data: Headline = {
  pagination: {
    limit: 100,
    offset: 0,
    count: 100,
    total: 10000,
  },
  data: [
    {
      author: "",
      title:
        "Building the financial foundations of a small business: An interior designer shares her journey and learnings",
      description:
        "The economic roller-coaster of recent times has undoubtedly been challenging, particularly for Australia’s self-employed.",
      url: "https://www.theage.com.au/business/small-business/building-the-financial-foundations-of-a-small-business-an-interior-designer-shares-her-journey-and-learnings-20230609-p5dfdd.html?ref=rss&utm_medium=rss&utm_source=rss_business",
      source: "The Age",
      image:
        "https://static.ffx.io/images/$zoom_0.5298%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_95/t_crop_custom/q_86%2Cf_auto/c726dac2123aabd72c41725a9870132bdf9234f6",
      category: "business",
      language: "en",
      country: "au",
      published_at: "2023-06-25T22:00:00+00:00",
    },
    {
      author: "Cointelegraph",
      title: "Token issuers in Japan exempt from 30% crypto tax on paper gains",
      description:
        "Token issuers in Japan exempt from 30% crypto tax on paper gains",
      url: "https://www.investing.com/news/cryptocurrency-news/token-issuers-in-japan-exempt-from-30-crypto-tax-on-paper-gains-3112625",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-25T22:20:10+00:00",
    },
    {
      author: null,
      title: "NHS performs less well than international peers, research shows",
      description:
        "UK health service is ‘middling at best’ with fewer doctors and nurses than comparable countries, says King’s Fund",
      url: "https://www.ft.com/content/0b73a259-fdb3-42bb-8a5b-bc7c586a8415",
      source: "Financial Times",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-25T23:01:19+00:00",
    },
    {
      author: "Bloomberg News",
      title: "T. Rowe Price on Intervention Alert as Yen Nears 150 per Dollar",
      description:
        "The yen is nearing levels that will likely prompt Japan to again jump in and defend the currency, according to T. Rowe Price’s Quentin Fitzsimmons.",
      url: "https://financialpost.com/pmn/business-pmn/t-rowe-price-on-intervention-alert-as-yen-nears-150-per-dollar",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T00:09:33+00:00",
    },
    {
      author: "BusinessWorld",
      title: "IDEAYALA 2023 puts spotlight on budding kiddie entrepreneurs",
      description:
        "This year’s IDEAYALA initiative challenged the next generation of budding entrepreneurs, aged five to 17, to form original businesses and put their ideas into action as they took over the gallery of Greenbelt 5 last May 20 and 21. Launched in 2014, IDEAYALA aims to inspire, train, and challenge the youth to innovate and develop [&#8230;]",
      url: "https://www.bworldonline.com/sparkup/2023/06/26/530408/ideayala-2023-puts-spotlight-on-budding-kiddie-entrepreneurs/",
      source: "Business World",
      image:
        "https://www.bworldonline.com/wp-content/uploads/2023/06/SPARK_R2-Snack-Stack-selling-booth-during-the-IDEAYALA-OL-300x224.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T00:50:44+00:00",
    },
    {
      author: "zee business",
      title: "Asian markets news: Russian turmoil tests safe-haven demand",
      description:
        "Asian markets news: Asian markets on Monday kick off what looks like a pretty light week for regional economic, policy and corporate drivers, with all eyes on how investors react to the extraordinary events in Russia over the weekend.",
      url: "https://www.zeebiz.com/markets/global-markets/news-asian-markets-today-news-index-russian-turmoil-dow-jones-241688",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T00:50:07+00:00",
    },
    {
      author: "Kamil Kowalcze",
      title: "Global Inflation Risk Rises Despite Lower Prices, Economist Says",
      description:
        "Global Inflation Risk Rises Despite Lower Prices, Economist Says",
      url: "https://www.bqprime.com/business/global-inflation-risk-rises-despite-lower-prices-economist-says",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T00:43:51+00:00",
    },
    {
      author: "Anjali Rai",
      title: "Indian Rupee Opens Firm Against The U.S Dollar",
      description: "Indian Rupee Opens Firm Against The U.S Dollar",
      url: "https://www.bqprime.com/markets/indian-rupee-opens-firm-against-the-us-dollar-6",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T03:55:39+00:00",
    },
    {
      author: "Isabel Vieira",
      title: "Wesfarmers ups bid to acquire SILK",
      description:
        "Wesfarmers' health division has upped its offer to $180 million to acquire SILK Laser Clinics after previously walking away from negotiations.",
      url: "https://www.businessnews.com.au/article/Wesfarmers-ups-bid-to-acquire-SILK",
      source: "Business News.com.au",
      image:
        "https://static.businessnews.com.au/sites/default/files/articles-2023-06/181220-246%201.jpg",
      category: "business",
      language: "en",
      country: "au",
      published_at: "2023-06-26T03:57:17+00:00",
    },
    {
      author: "Jeff Newmond",
      title: "IET Fellow Junade Ali Becomes Youngest Member Ever",
      description:
        "Today (Monday 26th June), Dr Junade Ali CEng has become the youngest Fellow of the Institution of Engineering and Technology (IET). Dr Ali, aged 27, is believed to be the youngest Fellow of any UK professional engineering institution. His unprecedented achievement is made all the more remarkable given that he is a secondary school drop-out [&#8230;]The post IET Fellow Junade Ali Becomes Youngest Member Ever first appeared on BusinessMole.",
      url: "https://www.businessmole.com/iet-fellow-junade-ali-becomes-youngest-member-ever/",
      source: "Businessmole",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T05:23:21+00:00",
    },
    {
      author: null,
      title:
        "Inflation below 5% but certain challenges still remain: RBI Governor Shaktikanta Das",
      description:
        "In the MPC announcements, the governor had said a close and continued vigil on the evolving inflation is absolutely necessary, especially as the monsoon outlook and the impact of El Nino remain uncertain. ",
      url: "https://www.businesstoday.in/latest/economy/story/inflation-below-5-but-certain-challenges-still-remain-rbi-governor-shaktikanta-das-387028-2023-06-26?utm_source=rssfeed",
      source: "Business Today | Latest Stock Market And Economy News India",
      image: null,
      category: "business",
      language: "en",
      country: "in",
      published_at: "2023-06-26T05:26:18+00:00",
    },
    {
      author: null,
      title:
        "&#039;Best finisher in the business&#039;: MS Dhoni magic gives Candy Crush massive boost, 3.6 downloads in just 3 hours!",
      description:
        "A recent viral video of Dhoni shows him onboard an IndiGo flight and playing Candy Crush to kill time on the flight. As this video went viral, surprisingly, along with MS Dhoni, even the hashtag Candy Crush began trending on Twitter’s trend list.",
      url: "https://www.businesstoday.in/latest/trends/story/best-finisher-in-the-business-ms-dhoni-magic-gives-candy-crush-massive-boost-36-downloads-in-just-3-hours-387048-2023-06-26?utm_source=rssfeed",
      source: "Business Today | Latest Stock Market And Economy News India",
      image: null,
      category: "business",
      language: "en",
      country: "in",
      published_at: "2023-06-26T07:17:10+00:00",
    },
    {
      author: "zee business",
      title: "Apple Vision Pro may turn any surface into touchscreen display",
      description:
        "An Apple Vision Pro developer has learned that the headset can create controls and displays, and make them appear on any surface in the user's room.",
      url: "https://www.zeebiz.com/technology/news-apple-apple-vision-pro-apple-iphone-apple-virtual-reality-artificial-intelligence-apple-vision-pro-launch-date-apple-vision-pro-price-apple-music-ios-241763",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T07:18:41+00:00",
    },
    {
      author: "zee business",
      title:
        "The Kerala Story filmmakers announce next film 'Bastar' to release in 2024",
      description:
        'Director Sudipto Sen and producer Vipul Shah, the duo behind "The Kerala Story", on Monday announced their next project "Bastar". According to the makers, "Bastar", based on a "true incident", will hit the screens on April 5, 2024.',
      url: "https://www.zeebiz.com/trending/entertainment/news-bastar-movie-bastar-release-date-director-sudipto-sen-producer-vipul-shah-sunshine-pictures-the-kerala-story-move-maker-241761",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T07:17:03+00:00",
    },
    {
      author: "BQ Contributor",
      title:
        "Dinesh Karthik Inaugurates T Natarajan's Cricket Academy In Tamil Nadu's Chinnappampatti; See Photos",
      description:
        "Dinesh Karthik Inaugurates T Natarajan's Cricket Academy In Tamil Nadu's Chinnappampatti; See Photos",
      url: "https://www.bqprime.com/sports/dinesh-karthik-inaugurates-t-natarajans-cricket-academy-in-tamil-nadus-chinnappampatti-see-photos-bqc",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T07:19:44+00:00",
    },
    {
      author: "Investing.com",
      title: "UBS Upgrades Moderna to Buy",
      description: "UBS Upgrades Moderna to Buy",
      url: "https://www.investing.com/news/pro/ubs-upgrades-moderna-to-buy-432SI-3112823",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T08:09:02+00:00",
    },
    {
      author: "Investing.com",
      title:
        "BMO Capital downgrades Celanese to 'market perform' with a price target of $119.00",
      description:
        "BMO Capital downgrades Celanese to 'market perform' with a price target of $119.00",
      url: "https://www.investing.com/news/pro/celanese-receives-investment-bank-analyst-rating-update-3112822",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/news/World_News_10_M_1440052130.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T08:05:41+00:00",
    },
    {
      author: "Investing.com",
      title:
        "UBS downgrades Alphabet A to 'neutral' with a price target of $132.00",
      description:
        "UBS downgrades Alphabet A to 'neutral' with a price target of $132.00",
      url: "https://www.investing.com/news/pro/google-inc-receives-investment-bank-analyst-rating-update-3112821",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image: "https://i-invdn-com.investing.com/news/LYNXNPEB7B00X_M.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T08:05:41+00:00",
    },
    {
      author: null,
      title: "Warning: OTLY is at high risk of performing badly",
      description: "Warning: OTLY is at high risk of performing badly",
      url: "https://seekingalpha.com/warnings/3982621-warning-otly-is-high-risk-of-performing-badly?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T08:25:29+00:00",
    },
    {
      author: "BQ Desk",
      title: "Income Tax Surveys Continue On Shree Cement Premises",
      description: "Income Tax Surveys Continue On Shree Cement Premises",
      url: "https://www.bqprime.com/markets/income-tax-surveys-continue-on-shree-cement-premises",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T08:30:47+00:00",
    },
    {
      author: "Angela Serratore",
      title: "$1.7 Million Homes in California",
      description:
        "An 1888 Craftsman home in Berkeley, a midcentury retreat in Palm Springs and a French Normandy house in Los Angeles.",
      url: "https://www.nytimes.com/2023/06/26/realestate/million-dollar-homes-california.html",
      source: "The New York Times",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T09:00:32+00:00",
    },
    {
      author: "GlobeNewswire",
      title:
        "That’s Crispy: Crispy Minis® Unveils Brand Partnership with Beloved Canadian Actress Annie Murphy",
      description:
        "MISSISSAUGA, Ontario, June 26, 2023 (GLOBE NEWSWIRE) &#8212; The Crispy Minis® brand is thrilled to announce an exciting new partnership with Canadian icon and actress, Annie Murphy. This partnership marks the beginning of a fresh era for the brand, focused on encouraging Canadians to embrace their crispy side. What’s crispy? It&#8217;s a vibe; being cute [&#8230;]",
      url: "https://financialpost.com/globe-newswire/thats-crispy-crispy-minis-unveils-brand-partnership-with-beloved-canadian-actress-annie-murphy",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:01:36+00:00",
    },
    {
      author: "GlobeNewswire",
      title: "First Quantum Provides Notice Of Second Quarter 2023 Results",
      description:
        "TORONTO, June 26, 2023 (GLOBE NEWSWIRE) &#8212; First Quantum Minerals Ltd. (“First Quantum” or “the Company”) (TSX: FM) will release second quarter 2023 financial and operating results on Tuesday, July 25, 2023 after the close of the Toronto Stock Exchange. The Company will host a conference call and webcast to discuss the results on Wednesday, [&#8230;]",
      url: "https://financialpost.com/globe-newswire/first-quantum-provides-notice-of-second-quarter-2023-results",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:01:23+00:00",
    },
    {
      author: "zee business",
      title:
        "Football transfer window: How transfers take place? How clubs invest billions - Explained",
      description:
        "Football transfer window: As most players are either enjoying the break after a long season or are on national duty, the main focus now turns to the clubs and the agents who represent the players for a change in the clubs, a better wage, or an extension of the contract. But all this might sound Greek to anyone who doesn't know how to speak football. For them, here's an explainer on each and every jargon that is used in a football transfer window.",
      url: "https://www.zeebiz.com/trending/sports/news-transfer-window-transfer-news-football-transfer-window-explainer-man-united-erik-ten-hag-real-madrid-messi-inter-miami-arsenal-transfer-mbappe-ronaldo-transfer-241803",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:15:48+00:00",
    },
    {
      author: "Business Wire",
      title:
        "New Found Provides Update on Industry-leading 3-D Seismic Survey at Its Queensway Gold Project",
      description:
        "VANCOUVER, British Columbia &#8212; New Found Gold Corp. (“New Found” or the “Company”) (TSX-V: NFG, NYSE-A: NFGC) is pleased to provide an update on its industry-leading 3-D seismic survey that will cover 47 km2 along the Appleton (“AFZ”) and JBP Fault Zones (“JBPFZ”) at its Queensway Project. New Found’s 100%-owned Queensway Project comprises a 1,662km2 [&#8230;]",
      url: "https://financialpost.com/pmn/business-wire-news-releases-pmn/new-found-provides-update-on-industry-leading-3-d-seismic-survey-at-its-queensway-gold-project",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:30:33+00:00",
    },
    {
      author: "zee business",
      title:
        "Taylor Swift asks fans during Eras Tour to be 'kind and gentle' on social media",
      description:
        "Pop-singer Taylor Swift gave a speech during her tour, where she asked her fans to act with “kindness and gentleness” on social media. This comes ahead of the release of her “Speak Now (Taylor's version)” album (not to be confused with her third album “Speak Now” from 2010).",
      url: "https://www.zeebiz.com/world/news-taylor-swift-news-taylor-swift-speech-american-singer-taylor-swift-speech-during-tour-taylor-worldwide-tour-mexico-japan-australia-singapore-europe-241805",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:25:40+00:00",
    },
    {
      author: null,
      title:
        "UBS downgrades Google-parent Alphabet, cites stiffer competition and generative A.I. headwinds",
      description:
        "The bank downgraded the tech giant to neutral from buy, albeit with a higher $132 per share price target compared to the previous $123 forecast.",
      url: "https://www.cnbc.com/2023/06/26/ubs-downgrades-googl-cites-stiffer-competition-and-generative-ai-headwinds.html",
      source: "Cnbc | World Business News Leader",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T10:28:00+00:00",
    },
    {
      author: "Business Matters",
      title:
        "Ryan Reynolds and Rob McElhenney join investors buying into Alpine F1 team",
      description:
        "Ryan Reynolds and Rob McElhenney have expanded their sporting portfolio by investing in Oxfordshire-based Formula One team Alpine Racing.Read more: Ryan Reynolds and Rob McElhenney join investors buying into Alpine F1 team",
      url: "https://bmmagazine.co.uk/get-funded/ryan-reynolds-and-rob-mcelhenney-join-investors-buying-into-alpine-f1-team/",
      source: "Business Matters | The Uk's Leading Sme Business Magazine",
      image: null,
      category: "business",
      language: "en",
      country: "gb",
      published_at: "2023-06-26T11:38:42+00:00",
    },
    {
      author: null,
      title:
        "Odisha man secures seat in IIM Ahmedabad after 9 unsuccessful attempts",
      description:
        "Nath gave his first CAT exam in 2014, and he has been appearing for the exam every year since then.",
      url: "https://www.businesstoday.in/latest/trends/story/odisha-man-secures-seat-in-iim-ahmedabad-after-9-unsuccessful-attempts-387113-2023-06-26?utm_source=rssfeed",
      source: "Business Today | Latest Stock Market And Economy News India",
      image: null,
      category: "business",
      language: "en",
      country: "in",
      published_at: "2023-06-26T12:20:51+00:00",
    },
    {
      author: "zee business",
      title:
        "Airtel Business CEO Ajaya Chitkara quits, enterprise arm divided into three segments",
      description:
        "The Chief Executive Officer of Bharti Airtel's enterprise arm Airtel Business, Ajay Chitkara, has resigned from the company, according to a filing.",
      url: "https://www.zeebiz.com/companies/news-airtel-bharti-airtel-airtel-business-ceo-resigns-ajay-chitkara-airtel-business-ceo-resigns-gopal-vittal-airtel-md-and-ceo-241819",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T12:22:26+00:00",
    },
    {
      author: null,
      title:
        "Sugarcane planting declines in Tamil Nadu due to high cultivation cost ",
      description:
        "Labour cost in the state is 2-3 times higher than Uttar Pradesh",
      url: "https://www.thehindubusinessline.com/economy/agri-business/sugarcane-planting-declines-in-tamil-nadu-due-to-high-cultivation-cost/article67011294.ece",
      source: "Business Line",
      image:
        "https://bl-i.thgim.com/public/companies/kmnd9g/article54411226.ece/alternates/LANDSCAPE_1200/gopalaratnamjpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T12:37:47+00:00",
    },
    {
      author: "Reuters",
      title:
        "GM's EV truck customers must wait for Tesla-compatible charge ports",
      description:
        "GM's EV truck customers must wait for Tesla-compatible charge ports",
      url: "https://www.investing.com/news/stock-market-news/gms-ev-truck-customers-must-wait-for-teslacompatible-charge-ports-3113329",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5P0FU_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T13:06:12+00:00",
    },
    {
      author: "Reuters",
      title: "Factbox-Governments race to regulate AI tools",
      description: "Factbox-Governments race to regulate AI tools",
      url: "https://www.investing.com/news/economy/factboxgovernments-race-to-regulate-ai-tools-3113327",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ501DY_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T13:05:44+00:00",
    },
    {
      author: "Business Wire",
      title:
        "3D BioFibR Enters the Bioprinting and 3D Cell Culture Market with the Launch of Two CollaFibR™ Tissue Engineering Products",
      description:
        "HALIFAX, Nova Scotia &#8212; 3DBioFibR, a leading innovator in tissue engineering, announced today it is launching two new collagen fiber products, μCollaFibR™ (pronounced micro-CollaFibR™) and CollaFibR™ 3D scaffold. Made using 3D BioFibR’s proprietary and new dry-spinning technology to create collagen fibers at commercial scales, these off-the-shelf products offer significant advantages for tissue engineering and tissue [&#8230;]",
      url: "https://financialpost.com/pmn/business-wire-news-releases-pmn/3d-biofibr-enters-the-bioprinting-and-3d-cell-culture-market-with-the-launch-of-two-collafibr-tissue-engineering-products",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T13:11:13+00:00",
    },
    {
      author: "Business Wire",
      title:
        "Xtellar Introduces Industry-First Flexible Bio-Based EVA Pellets for Large-Format 3D Printing",
      description:
        "Bio-based flexible EVA (Ethylene Vinyl Acetate) pellets offer sustainable, lightweight, flexible capabilities for large-format additive manufacturing. PHILADELPHIA &#8212; Xtellar, a market leader in 3D printing materials innovation formed by combining Braskem’s 3D materials division and Taulman3D, has introduced an industry-first for large-format 3D printing. Launched at RAPID + TCT 2023 to a strong reception, Xtellar’s [&#8230;]",
      url: "https://financialpost.com/pmn/business-wire-news-releases-pmn/xtellar-introduces-industry-first-flexible-bio-based-eva-pellets-for-large-format-3d-printing",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T13:07:36+00:00",
    },
    {
      author: null,
      title:
        "IBM to buy software co Apptio for $4.6 bn to bolster cloud offerings",
      description:
        "IBM said it will finance the transaction with cash on hand and expects the deal to close in the latter half of 2023.",
      url: "https://www.businesstoday.in/latest/corporate/story/ibm-to-buy-software-co-apptio-for-46-bn-to-bolster-cloud-offerings-387128-2023-06-26?utm_source=rssfeed",
      source: "Business Today | Latest Stock Market And Economy News India",
      image: null,
      category: "business",
      language: "en",
      country: "in",
      published_at: "2023-06-26T13:27:33+00:00",
    },
    {
      author: "Shira Sapir",
      title: "Wissotzky Tea declared monopoly by Competition Authority",
      description:
        "The Israel Competition Authority found that Wissotzky's share in sales of green tea and herbal tea to retailers is higher than 70%.",
      url: "https://en.globes.co.il/en/article-1001450440#utm_source=RSS",
      source: "Globes English | Israel Business Arena",
      image:
        "https://res.cloudinary.com/globes/image/upload/t_800X392/v1613215144/old/1344130.jpg",
      category: "business",
      language: "en",
      country: "il",
      published_at: "2023-06-26T14:10:27+00:00",
    },
    {
      author: null,
      title:
        "Zymeworks joins Russell 3000, Russell 2000, and Russell microcap indexes",
      description:
        "Zymeworks joins Russell 3000, Russell 2000, and Russell microcap indexes",
      url: "https://seekingalpha.com/news/3982775-zymeworks-joins-russell-3000-russell-2000-and-russell-microcap-indexes?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T14:26:50+00:00",
    },
    {
      author: null,
      title: "Maiden Holdings rejoins Russell 3000 index",
      description: "Maiden Holdings rejoins Russell 3000 index",
      url: "https://seekingalpha.com/news/3982785-maiden-holdings-rejoins-russell-3000-index?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T14:35:23+00:00",
    },
    {
      author: "Reuters",
      title:
        "Analysis-Mutiny lays bare prospect for Putin of 'forever war' in Ukraine",
      description:
        "Analysis-Mutiny lays bare prospect for Putin of 'forever war' in Ukraine",
      url: "https://www.investing.com/news/world-news/analysismutiny-lays-bare-prospect-for-putin-of-forever-war-in-ukraine-3112855",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5P08A_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T14:52:08+00:00",
    },
    {
      author: "zee business",
      title: "Boult sixth anniversary offers discounts founder Varun Gupta",
      description:
        "According to the IDC report, Boult has secured 366.5 per cent year-on-year growth, holding a significant 9.3 per cent market share in the first quarter of 2023.",
      url: "https://www.zeebiz.com/technology/news-boult-sixth-anniversary-offers-discounts-founder-varun-gupta-241840",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T14:52:24+00:00",
    },
    {
      author: "Mariam Ahmed",
      title:
        "Charleston TV station hires Roberts as morning news anchor/reporter",
      description:
        "Shelbey Roberts has joined CBS station WCSC-TV Ch. 5 in Charleston, S.C. as a morning news anchor/reporter. Recently, she was at WMBD-TV Ch. 31, a CBS affiliate in Peoria, Ill. There, Roberts held the posts of morning news anchor, reporter, noon producer, evening news anchor and reporter. She also worked as a weekend multimedia journalist [&#8230;]",
      url: "https://talkingbiznews.com/media-moves/charleston-tv-station-hires-roberts-as-morning-news-anchor-reporter/",
      source: "Talking Biz News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:13:02+00:00",
    },
    {
      author: null,
      title: "J&J submits application to EMA for combination PAH drug",
      description: "J&J submits application to EMA for combination PAH drug",
      url: "https://seekingalpha.com/news/3982795-johnson-johnson-janssen-submits-application-ema-combination-pah-drug?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:10:25+00:00",
    },
    {
      author: "aplatas@thebtngroup.com (Angelique Platas)",
      title: "Hilton to Hire 1,500 Refugees in EU",
      description:
        "Hilton Worldwide plans to hire 1,500 refugees throughout Europe during the next three years, the company announced last week during the Tent Foundation European Business Summit.&#160; &#160;",
      url: "https://www.businesstravelnews.com/Lodging/Hilton-to-Hire-1500-Refugees-in-EU?utm_source=website&utm_medium=RSS&utm_campaign=btnrss2018",
      source: "Business Travel News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:15:07+00:00",
    },
    {
      author: "Mariam Ahmed",
      title: "The Telegraph taps Diver to serve as U.S. editor",
      description:
        "The Telegraph has promoted Tony Diver to the post of U.S. editor. Recently, he served as a Whitehall correspondent and acting Sunday political editor. Diver has been with The Telegraph for more than four years, in roles including news reporter and political correspondent. He also freelanced for The Telegraph, The Times, BuzzFeed, The Spectator, Radio [&#8230;]",
      url: "https://talkingbiznews.com/media-moves/the-telegraph-taps-diver-to-serve-as-u-s-editor/",
      source: "Talking Biz News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:59:24+00:00",
    },
    {
      author: "Mariam Ahmed",
      title: "NY Times appoints Kendall-Ball photo department staff editor",
      description:
        "The following excerpt was sent out from The New York Times&#8217; Meaghan Looram and Clinton Cargill: We are delighted to welcome Greg Kendall-Ball to the Photo department as a staff editor. He will join the digital team, focused on Live and Express coverage and home screen curation, reporting to Clinton. Greg began his journalism career [&#8230;]",
      url: "https://talkingbiznews.com/media-moves/ny-times-appoints-kendall-ball-photo-department-staff-editor/",
      source: "Talking Biz News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:58:40+00:00",
    },
    {
      author: "Investing.com",
      title:
        "Macquarie maintains Evolution Mining at 'underperform' with a price target of AUD3.10",
      description:
        "Macquarie maintains Evolution Mining at 'underperform' with a price target of AUD3.10",
      url: "https://www.investing.com/news/pro/evolution-mining-receives-investment-bank-analyst-rating-update-3113501",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/news/World_News_10_M_1440052130.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:58:48+00:00",
    },
    {
      author: "Sahyaja S",
      title:
        "Zee's Subhash Chandra Only Holds A Titular Chairmanship, Says His Counsel At SAT",
      description:
        "Zee's Subhash Chandra Only Holds A Titular Chairmanship, Says His Counsel At SAT",
      url: "https://www.bqprime.com/law-and-policy/zees-subhash-chandra-only-holds-a-titular-chairmanship-says-his-counsel-at-sat",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T15:58:59+00:00",
    },
    {
      author: "BusinessWorld",
      title: "Errant companies swamp SEC with amnesty filings",
      description:
        "THE SECURITIES and Exchange Commission (SEC) has noted a large number of companies filing for amnesty after failing to submit regulatory requirements, its top official said on Monday. “We are very busy now with our amnesty program. We had to sort out schedules and processes kasi ang daming nag-a-apply (because there are plenty of applicants),” [&#8230;]",
      url: "https://www.bworldonline.com/corporate/2023/06/27/530838/errant-companies-swamp-sec-with-amnesty-filings/",
      source: "Business World",
      image:
        "https://www.bworldonline.com/wp-content/uploads/2022/08/SEC-logo-300x169.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:07:02+00:00",
    },
    {
      author: "BusinessWorld",
      title: "Are the Oscars going to take animated films more seriously?",
      description:
        "“ANIMATION is cinema. Animation is not a genre. And, animation is ready to be taken to the next step — we are all ready for it, please help us, keep animation in the conversation.” This was Guillermo del Toro’s testament accepting the Academy Award for Best Animated Feature Film in 2023 for Guillermo del Toro’s [&#8230;]",
      url: "https://www.bworldonline.com/arts-and-leisure/2023/06/27/530690/are-the-oscars-going-to-take-animated-films-more-seriously/",
      source: "Business World",
      image:
        "https://www.bworldonline.com/wp-content/uploads/2023/06/spiderverse-300x169.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:06:09+00:00",
    },
    {
      author: "BusinessWorld",
      title: "Grab commits to livelihood plan despite restructuring",
      description:
        "MYTAXI.PH, Inc., the company behind Grab Philippines, said the job layoff announced last week would not affect its commitment to provide 500,000 livelihood opportunities to Filipinos. “The Philippines has always been an important market for Grab. We remain steadfast in our promise to create 500,000 livelihood opportunities in the Philippines and will continue to make [&#8230;]",
      url: "https://www.bworldonline.com/corporate/2023/06/27/530837/grab-commits-to-livelihood-plan-despite-restructuring/",
      source: "Business World",
      image:
        "https://www.bworldonline.com/wp-content/uploads/2021/09/Grab-logo-300x169.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:06:02+00:00",
    },
    {
      author: null,
      title: "Defence stocks fall after aborted uprising in Russia",
      description:
        "Some investors take profits on high-flying sector, betting that challenge to Putin’s regime could shorten Ukraine war",
      url: "https://www.ft.com/content/ede7f80e-6e84-40fe-8ae7-131b6cc6884f",
      source: "Financial Times",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:22:06+00:00",
    },
    {
      author: "D-e_v@IS",
      title: "The Most Influential Woman in Mortgage Industry – 2023, June2023",
      description:
        "The post The Most Influential Woman in Mortgage Industry &#8211; 2023, June2023 appeared first on Insights Success.",
      url: "https://insightssuccess.com/the-most-influential-woman-in-mortgage-industry-2023/",
      source: "Insights Success",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:41:55+00:00",
    },
    {
      author: null,
      title: "NKLA and EOSE among industrial movers",
      description: "NKLA and EOSE among industrial movers",
      url: "https://seekingalpha.com/news/3982840-nkla-and-eose-among-industrial-movers?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T16:57:01+00:00",
    },
    {
      author: "Business Wire",
      title:
        "Health Care Administrative Professionals Vote in Favour of Strike",
      description:
        "HALIFAX, Nova Scotia &#8212; Administrative Professionals, represented by CUPE, NSGEU, and Unifor under the Council of Health Administrative Unions, voted strongly in favour of strike action following their rejection of a tentative agreement in April, with 81.5% of those who voted authorizing a strike. The three unions represent approximately 5000 members from all hospital sites [&#8230;]",
      url: "https://financialpost.com/pmn/business-wire-news-releases-pmn/health-care-administrative-professionals-vote-in-favour-of-strike",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T17:30:20+00:00",
    },
    {
      author: "PTI",
      title:
        "Instant Line Of Credit, Industry Networking Top Priorities Of MSMEs: Survey",
      description:
        "Instant Line Of Credit, Industry Networking Top Priorities Of MSMEs: Survey",
      url: "https://www.bqprime.com/business/instant-line-of-credit-industry-networking-top-priorities-of-msmes-survey",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T17:52:55+00:00",
    },
    {
      author: null,
      title: "Nordson to acquire ARAG Group for €960M",
      description: "Nordson to acquire ARAG Group for €960M",
      url: "https://seekingalpha.com/news/3982859-nordson-to-acquire-arag-group-for-960m?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T17:51:48+00:00",
    },
    {
      author: null,
      title: "Orange county Bancorp joins Russell 2000 Index",
      description: "Orange county Bancorp joins Russell 2000 Index",
      url: "https://seekingalpha.com/news/3982863-orange-county-bancorp-joins-russell-2000-index?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T18:06:24+00:00",
    },
    {
      author: null,
      title:
        "WisdomTree Emerging Markets Quality Dividend Growth Fund declares quarterly distribution of $0.1500",
      description:
        "WisdomTree Emerging Markets Quality Dividend Growth Fund declares quarterly distribution of $0.1500",
      url: "https://seekingalpha.com/news/3982917-wisdomtree-emerging-markets-quality-dividend-growth-fund-declares-quarterly-distribution-of-01500?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T18:52:02+00:00",
    },
    {
      author: null,
      title: "Teleflex recalls some catheters due to leakage concerns",
      description: "Teleflex recalls some catheters due to leakage concerns",
      url: "https://seekingalpha.com/news/3982913-teleflex-recalls-some-catheters-due-leakage-concerns?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T18:51:01+00:00",
    },
    {
      author: "GlobeNewswire",
      title: "Major Drilling Announces Publication of Sustainability Report",
      description:
        "MONCTON, New Brunswick, June 26, 2023 (GLOBE NEWSWIRE) &#8212; Major Drilling Group International Inc. (“Major Drilling” or the “Company”) (TSX: MDI), a leading provider of specialized drilling services to the mining sector, today published its Sustainability Report covering the reporting period of calendar 2022.  “We’re proud to announce the publication of our second annual Sustainability [&#8230;]",
      url: "https://financialpost.com/globe-newswire/major-drilling-announces-publication-of-sustainability-report",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T20:30:22+00:00",
    },
    {
      author: "Daniel Tencer",
      title:
        "82% of 18-44 year-olds have posted a video online in the past year, YouTube poll finds",
      description:
        "In the world of digital media, virtually everyone is a creator – a fact that has significant implications for the music industry. According to the 2023 edition of the YouTube Culture and Trends Report, which the Alphabet-owned video streaming service released to coincide with the opening of the VidCon 2023 conference in Anaheim, Calif., last &#8230; ContinuedSource",
      url: "https://www.musicbusinessworldwide.com/82-of-18-44-year-olds-have-posted-a-video-online-in-the-past-year-youtube-poll-finds/",
      source: "Music Business Worldwide",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T21:05:47+00:00",
    },
    {
      author: "Reuters",
      title: "Russia's Putin says he let mutiny continue to avoid bloodshed",
      description:
        "Russia's Putin says he let mutiny continue to avoid bloodshed",
      url: "https://www.investing.com/news/world-news/russias-putin-thanks-those-wagner-fighters-who-helped-avoid-bloodshed-3113594",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5P0QQ_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-26T21:06:09+00:00",
    },
    {
      author: "GlobeNewswire",
      title:
        "Jourdan Closes Second Tranche of Flow-Through Private Placement Financing",
      description:
        "NOT FOR DISTRIBUTION TO UNITED STATES NEWS WIRE SERVICES OR DISSEMINATION IN THE UNITED STATES TORONTO, June 26, 2023 (GLOBE NEWSWIRE) &#8212;  JOURDAN RESOURCES INC. (TSXV: JOR; FRA: 2JR1) (“Jourdan” or the “Company“) is pleased to announce that it has closed its second tranche of a previously announced non-brokered private placement financing of common shares [&#8230;]",
      url: "https://financialpost.com/globe-newswire/jourdan-closes-second-tranche-of-flow-through-private-placement-financing",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T00:46:01+00:00",
    },
    {
      author: "GlobeNewswire",
      title:
        "Gatos Silver Completes 2021 and 2022 Securities Filings and Announces Date for 2023 Annual Stockholders’ Meeting",
      description:
        "VANCOUVER, British Columbia, June 26, 2023 (GLOBE NEWSWIRE) &#8212; Gatos Silver, Inc. (NYSE/TSX: GATO) (“Gatos Silver” or the “Company”) today announced that it has completed disclosure of outstanding 2021 and 2022 securities regulatory filings and has reached an agreement in principle to settle the US class action lawsuit. The Company also today announced that it [&#8230;]",
      url: "https://financialpost.com/globe-newswire/gatos-silver-completes-2021-and-2022-securities-filings-and-announces-date-for-2023-annual-stockholders-meeting",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T02:52:13+00:00",
    },
    {
      author: "BQ Contributor",
      title:
        "PM Modi To Flag Off These 5 New Vande Bharat Express Trains On June 27",
      description:
        "PM Modi To Flag Off These 5 New Vande Bharat Express Trains On June 27",
      url: "https://www.bqprime.com/web-stories/pm-modi-to-flag-off-these-5-new-vande-bharat-express-trains-on-june-27-bqc",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T02:51:38+00:00",
    },
    {
      author: null,
      title:
        "China is still on track to hit its growth target, Premier Li Qiang says",
      description:
        "Chinese Premier Li Qiang said Tuesday his country was still on track to reach its annual growth target of around 5%.",
      url: "https://www.cnbc.com/2023/06/27/china-on-track-to-hit-its-growth-target-li-qiang-says-at-wef-tianjin.html",
      source: "Cnbc | World Business News Leader",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T02:56:00+00:00",
    },
    {
      author: "Reuters",
      title: "Thai May exports drop 4.6% y/y, beat forecast",
      description: "Thai May exports drop 4.6% y/y, beat forecast",
      url: "https://www.investing.com/news/economic-indicators/thai-may-exports-drop-46-yy-beat-forecast-3113746",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5Q03P_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T03:56:01+00:00",
    },
    {
      author: "Reuters",
      title:
        "China's growth to be higher in Q2, projected to hit annual 5% target - Premier Li",
      description:
        "China's growth to be higher in Q2, projected to hit annual 5% target - Premier Li",
      url: "https://www.investing.com/news/economy/chinas-growth-to-be-higher-in-q2-projected-to-hit-annual-5-target--premier-li-3113744",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5Q03N_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T03:55:41+00:00",
    },
    {
      author: "zee business",
      title:
        "FIRST TRADE: Sensex rises more than 200 pts, Nifty tops 18,750; Infosys, HDFC Bank top gainers",
      description:
        "Stock market today: At the time of writing this news, the S&P BSE Sensex was trading 222 points, or 0.35 per cent higher at 63,191.63 levels while the NSE's Nifty was ruling at 18,757.95, up 67 points, or 0.36 per cent.",
      url: "https://www.zeebiz.com/market-news/news-first-trade-sensex-rises-more-than-200-pts-nifty-tops-18750-infosys-hdfc-bank-top-gainers-241872",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T03:52:57+00:00",
    },
    {
      author: "Vivek Punj",
      title: "Cyient DLM IPO Subscription Status: Day 1 Live Updates",
      description: "Cyient DLM IPO Subscription Status: Day 1 Live Updates",
      url: "https://www.bqprime.com/markets/cyient-dlm-ipo-subscription-status-day-1-live-updates",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T04:52:16+00:00",
    },
    {
      author: "zee business",
      title:
        "PM Modi to flag off five new Vande Bharat Express trains today; check out schedule, time table, routes, other important details",
      description:
        "PM Narendra Modi to flag off Vande Bharat Express trains during MP visit: India is all set to witness the launch of new semi-high-speed trains in the country as Prime Minister Narendra Modi will flag off five new Vande Bharat trains from Bhopal in Madhya Pradesh during his one-da",
      url: "https://www.zeebiz.com/indian-railways/news-pm-modi-5-vande-bharat-express-trains-flag-off-today-june-27-mp-visit-timings-routes-time-table-national-sickle-cell-anaemia-elimination-mission-launch-241894",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T05:29:44+00:00",
    },
    {
      author: "zee business",
      title:
        "Gold and Silver price today (June 27, 2023): Precious metals trade in green; Gold above Rs 58,000, Silver near Rs 70,000",
      description:
        "Gold and Silver price today (June 27, 2023): MCX gold futures (Aug 4) were up Rs117 or 0.2 per cent at Rs 58,529 per 10 grams. Check out city wise prices of 24k gold.",
      url: "https://www.zeebiz.com/markets/commodities/news-gold-silver-price-june-27-2023-check-24k-gold-price-mumbai-delhi-kolkata-chennai-and-other-cities-241896",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T05:28:48+00:00",
    },
    {
      author: "Nick Toscano",
      title:
        "BHP chief warns race for green metals needs more than subsidy ‘sugar hit’",
      description:
        "The world’s top miner says Australia doesn’t need to match the United States’ critical minerals subsidies, but has fired fresh warnings over regulatory changes.",
      url: "https://www.smh.com.au/business/companies/bhp-chief-warns-race-for-green-metals-needs-more-than-subsidy-sugar-hit-20230627-p5djuc.html?ref=rss&utm_medium=rss&utm_source=rss_business",
      source: "The Sydney Morning Herald",
      image:
        "https://static.ffx.io/images/$zoom_0.256%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_146%2C$y_0/t_crop_custom/q_86%2Cf_jpg/931f8843ba95f0ce0b15a69fc6ede98a0355674b",
      category: "business",
      language: "en",
      country: "au",
      published_at: "2023-06-27T05:51:17+00:00",
    },
    {
      author: "BQ Contributor",
      title:
        "ODI World Cup 2023 Schedule Announced: Full List Of Matches & Fixtures For ICC Cricket World Cup 2023",
      description:
        "ODI World Cup 2023 Schedule Announced: Full List Of Matches & Fixtures For ICC Cricket World Cup 2023",
      url: "https://www.bqprime.com/sports/odi-world-cup-2023-schedule-announced-full-list-of-matches-fixtures-for-icc-cricket-world-cup-2023-bqc",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T06:37:37+00:00",
    },
    {
      author: "Investing.com",
      title:
        "Deutsche Bank maintains Heineken at 'buy' with a price target of EUR145.00",
      description:
        "Deutsche Bank maintains Heineken at 'buy' with a price target of EUR145.00",
      url: "https://www.investing.com/news/pro/heineken-receives-investment-bank-analyst-rating-update-3113865",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/news/World_News_8_M_1440052125.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T07:16:37+00:00",
    },
    {
      author: "Investing.com",
      title:
        "Deutsche Bank maintains Eni SpA at 'buy' with a price target of EUR15.80",
      description:
        "Deutsche Bank maintains Eni SpA at 'buy' with a price target of EUR15.80",
      url: "https://www.investing.com/news/pro/eni-receives-investment-bank-analyst-rating-update-3113862",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/news/World_News_9_M_1440052127.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T07:16:36+00:00",
    },
    {
      author: "Business Matters",
      title: "Record numbers looking to kickstart new careers in cyber",
      description:
        "A record number of people are looking to embark on a new career in cyber this year through applications to the government’s Upskill in Cyber programme.Read more: Record numbers looking to kickstart new careers in cyber",
      url: "https://bmmagazine.co.uk/news/record-numbers-looking-to-kickstart-new-careers-in-cyber/",
      source: "Business Matters | The Uk's Leading Sme Business Magazine",
      image: null,
      category: "business",
      language: "en",
      country: "gb",
      published_at: "2023-06-27T07:13:02+00:00",
    },
    {
      author: "Vikas Srivastava",
      title: "India's Biogas Sector Poised For Growth",
      description: "India's Biogas Sector Poised For Growth",
      url: "https://www.bqprime.com/business/indias-biogas-sector-poised-for-growth",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T07:33:46+00:00",
    },
    {
      author: "The Associated Press",
      title:
        "Corruption trial begins for former Indonesia IT minister over mobile phone tower project",
      description:
        "JAKARTA, Indonesia (AP) &#8212; Indonesia&#8217;s anti-graft court on Tuesday began a trial for a former communication and information technology minister who was charged with corruption over the construction of mobile phone transmission towers in remote parts of the country. Prosecutors allege that Johnny G. Plate changed the terms of the 8 trillion rupiah ($533 million) [&#8230;]",
      url: "https://financialpost.com/pmn/business-pmn/corruption-trial-begins-for-former-indonesia-it-minister-over-mobile-phone-tower-project",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T07:36:53+00:00",
    },
    {
      author: "Investing.com",
      title:
        "Berenberg initiates coverage of Informa at 'buy' with a price target of GBP8.20",
      description:
        "Berenberg initiates coverage of Informa at 'buy' with a price target of GBP8.20",
      url: "https://www.investing.com/news/pro/informa-receives-investment-bank-analyst-rating-update-3113889",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/news/international_newspapers_108x81.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T07:46:35+00:00",
    },
    {
      author: "ICICI Securities",
      title:
        "Indian Banks' Balance Sheet Strength Is Strong And Likely To Remain So: ICICI Securities' Thematic View",
      description:
        "Indian Banks' Balance Sheet Strength Is Strong And Likely To Remain So: ICICI Securities' Thematic View",
      url: "https://www.bqprime.com/research-reports/indian-banks-balance-sheet-strength-is-strong-and-likely-to-remain-so-icici-securities-thematic-view",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T08:53:35+00:00",
    },
    {
      author: "Business Matters",
      title:
        "Windfall tax revenue set to slump 40 per cent thanks to falling oil and gas prices",
      description:
        "The sharp fall in the price of oil and gas will lead to a huge drop in revenue from the government’s windfall tax. Read more: Windfall tax revenue set to slump 40 per cent thanks to falling oil and gas prices",
      url: "https://bmmagazine.co.uk/news/windfall-tax-revenue-set-to-slump-40-per-cent-thanks-to-falling-oil-and-gas-prices/",
      source: "Business Matters | The Uk's Leading Sme Business Magazine",
      image: null,
      category: "business",
      language: "en",
      country: "gb",
      published_at: "2023-06-27T09:44:57+00:00",
    },
    {
      author: null,
      title:
        "ONDC aims for one lakh daily transactions, explores export enablement",
      description:
        "ONDC expects to demonstrate international transactions this year and anticipates significant growth in B2B transactions.",
      url: "https://www.thehindubusinessline.com/news/national/ondc-aims-for-one-lakh-daily-transactions-explores-export-enablement/article67015011.ece",
      source: "Business Line",
      image:
        "https://bl-i.thgim.com/public/incoming/lbt20l/article66934774.ece/alternates/LANDSCAPE_1200/IMG_BL0506_Corp_T_Koshy__2_1_UPBADUPT.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T10:02:19+00:00",
    },
    {
      author: null,
      title:
        "No transactions and settlements in various markets regulated by RBI June 29",
      description:
        "The settlement of all outstanding transactions due on June 29, 2023 will accordingly get postponed to the next working day",
      url: "https://www.thehindubusinessline.com/money-and-banking/no-transactions-and-settlements-in-various-markets-regulated-by-rbi-june-29/article67014944.ece",
      source: "Business Line",
      image:
        "https://bl-i.thgim.com/public/todays-paper/tp-others/tp-variety/zcnzw2/article67006504.ece/alternates/LANDSCAPE_1200/The-ongoing-%E2%80%98re%2BGSKBDB03C.4.jpg.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T10:00:47+00:00",
    },
    {
      author: "Jiya Saini",
      title:
        "An Expert Reveals How Heatstroke Can Be Mistaken for Heat Exhaustion – Signs and What You Can Do About It",
      description:
        "How To Tell If You Have a Heat Stroke or Just Heat Exhaustion &#8211; The key differentiators Heatstroke is a serious condition that commonly occurs due to exposure to hot weather or strenuous exercise. It occurs when the body is unable to cool itself effectively, leading to dangerously high body temperatures. While anyone can be [&#8230;]The post An Expert Reveals How Heatstroke Can Be Mistaken for Heat Exhaustion &#8211; Signs and What You Can Do About It appeared first on Revyuh.",
      url: "https://www.revyuh.com/news/lifestyle/health-and-fitness/an-expert-reveals-how-heatstroke-can-be-mistaken-for-heat-exhaustion-signs-and-what-you-can-do-about-it/",
      source: "Revyuh Media",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T10:36:45+00:00",
    },
    {
      author: "Reuters",
      title:
        "Brookfield reinsurance arm offers to buy American Equity in $4.3 billion deal",
      description:
        "Brookfield reinsurance arm offers to buy American Equity in $4.3 billion deal",
      url: "https://www.investing.com/news/stock-market-news/brookfield-reinsurance-arm-offers-to-buy-american-equity-in-43-billion-deal-3114191",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5Q0DC_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T10:51:36+00:00",
    },
    {
      author: "Sahyaja S",
      title:
        "SAT Reserves Order In Punit Goenka, Subhash Chandra's Appeal Against SEBI Ban",
      description:
        "SAT Reserves Order In Punit Goenka, Subhash Chandra's Appeal Against SEBI Ban",
      url: "https://www.bqprime.com/business/sat-reserves-order-in-punit-goenka-subhash-chandras-appeal-against-sebi-ban",
      source: "Bloomberg | Latest And Live Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T10:52:38+00:00",
    },
    {
      author: null,
      title: "CACI bags $5.7B worth service agreement for US Air Force",
      description: "CACI bags $5.7B worth service agreement for US Air Force",
      url: "https://seekingalpha.com/news/3983095-caci-bags-57b-worth-service-agreement-for-us-air-force?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T11:52:00+00:00",
    },
    {
      author: null,
      title: "Canada inflation drops to 3.4% in May",
      description: "Canada inflation drops to 3.4% in May",
      url: "https://seekingalpha.com/news/3983121-canada-inflation-drops-to-34-in-may?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T12:36:05+00:00",
    },
    {
      author: "Reuters",
      title: "BOJ may tweak yield control policy in Oct - ex-board member",
      description:
        "BOJ may tweak yield control policy in Oct - ex-board member",
      url: "https://www.investing.com/news/economy/boj-may-tweak-yield-control-policy-in-oct--exboard-member-3114351",
      source: "Investing.com | Stock Market Quotes &amp; Financial News",
      image:
        "https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ5Q07R_L.jpg",
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T12:52:13+00:00",
    },
    {
      author: null,
      title:
        "Evolve state global real estate yield  fund declares CAD 0.15 dividend",
      description:
        "Evolve state global real estate yield  fund declares CAD 0.15 dividend",
      url: "https://seekingalpha.com/news/3983145-evolve-state-global-real-estate-yield-fund-declares-cad-015-dividend?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T13:07:17+00:00",
    },
    {
      author: null,
      title: "Evolve US Banks Enhanced Yield Fund declares CAD 0.125 dividend",
      description:
        "Evolve US Banks Enhanced Yield Fund declares CAD 0.125 dividend",
      url: "https://seekingalpha.com/news/3983140-evolve-us-banks-enhanced-yield-fund-declares-cad-0125-dividend?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T13:06:45+00:00",
    },
    {
      author: "Chris Roush",
      title: "China bans financial writer from Weibo",
      description:
        "China banned a prominent finance writer and two of his peers from social media platform Weibo for commenting about the country’s stock market and unemployment rate, according to a Bloomberg News story. Bloomberg News reports, &#8220;Wu Xiaobo and two other writers who weren’t fully named &#8216;attacked and undermined&#8217; Chinese policy and spread &#8216;negative and harmful [&#8230;]",
      url: "https://talkingbiznews.com/media-news/china-bans-financial-writer-from-weibo/",
      source: "Talking Biz News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T13:45:12+00:00",
    },
    {
      author: "Manish Saini",
      title:
        "The Unexpected Symptoms That May Warn of Alzheimer’s Looming After Diminishing Sense of Smell",
      description:
        "Diminishing sense of smell influences many aspects of our health &#8211; and this may be the one that puts our life at greater danger of neurodegenerative diseases such as Alzheimer’s disease and Parkinson’s disease, as well as early death. Hyposmia refers to a reduction in the sense of smell or a diminished ability to detect [&#8230;]The post The Unexpected Symptoms That May Warn of Alzheimer&#8217;s Looming After Diminishing Sense of Smell appeared first on Revyuh.",
      url: "https://www.revyuh.com/news/lifestyle/health-and-fitness/the-unexpected-symptoms-that-may-warn-of-alzheimers-looming-after-diminishing-sense-of-smell/",
      source: "Revyuh Media",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T14:12:03+00:00",
    },
    {
      author: "Mariam Ahmed",
      title: "The Drum appoints McCarthy opinion editor",
      description:
        "The Drum has tapped John McCarthy to serve as opinion editor. Recently, he held the post of online senior reporter. McCarthy has been with the The Drum for nine years. During this time, he has held the posts of reporter, media editor and online senior reporter. He was an online senior reporter at The Drum [&#8230;]",
      url: "https://talkingbiznews.com/media-moves/the-drum-appoints-mccarthy-opinion-editor/",
      source: "Talking Biz News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T15:04:22+00:00",
    },
    {
      author: "zee business",
      title:
        "Sebi prescribes methods to REITs, InvITs for compliance with 25% minimum public holding rules",
      description:
        "Markets regulator Sebi on Tuesday provided methods such as an offer for-sale mechanism, rights issue and issuance of bonuses to unitholders of REITs and InvITs to achieve compliance with the 25 per cent minimum public holding requirement.",
      url: "https://www.zeebiz.com/market-news/news-indian-reits-invits-sebi-minimum-public-holdings-rules-compliance-of-25-real-estate-investment-trust-infrastructure-investment-trust-offer-for-sale-nse-bse-sebi-nifty-sensex-241982",
      source: "Zee Business",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T15:23:01+00:00",
    },
    {
      author: "Murray Stassen",
      title:
        "Joe Cocker estate strikes catalog deal with Irving Azoff’s Iconic Artists Group",
      description:
        "'We are honored to work with Joe’s family and be the custodians of his powerful body of work,' said Iconic President, Jimmy EdwardsSource",
      url: "https://www.musicbusinessworldwide.com/joe-cocker-estate-strikes-deal-with-irving-azoffs-iconic-artists-group/",
      source: "Music Business Worldwide",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T15:53:23+00:00",
    },
    {
      author: null,
      title:
        "Nasdaq, S&P, Dow boosted by consumer discretionary, tech stocks; economic data in focus",
      description:
        "Nasdaq, S&P, Dow boosted by consumer discretionary, tech stocks; economic data in focus",
      url: "https://seekingalpha.com/news/3983262-stock-market-news-today-nasdaq-dow-jones-sp500-economic-data?utm_source=feed_news_all&utm_medium=referral",
      source: "Seeking Alpha",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T15:50:44+00:00",
    },
    {
      author: "GlobeNewswire",
      title:
        "TerrAscend Closes US$25 Million Commercial Loan with Stearns Bank",
      description:
        "Proceeds will be used to pay down higher-interest debt, reducing overall interest expense TORONTO, June 27, 2023 (GLOBE NEWSWIRE) &#8212; TerrAscend Corp. (&#8220;TerrAscend&#8221; or the &#8220;Company&#8221;) (CSE: TER) (OTCQX: TRSSF), a leading North American cannabis operator, today announced that it has closed on a US$25 million commercial loan with Stearns Bank (the “Loan”). The proceeds [&#8230;]",
      url: "https://financialpost.com/globe-newswire/terrascend-closes-us25-million-commercial-loan-with-stearns-bank",
      source: "Financial Post | Canada Business News",
      image: null,
      category: "business",
      language: "en",
      country: "us",
      published_at: "2023-06-27T16:00:48+00:00",
    },
  ],
};
