import { Headline } from "@/types";

export const data: Headline = {
  pagination: {
    limit: 100,
    offset: 0,
    count: 100,
    total: 1287,
  },
  data: [
    {
      author: "Benj Edwards",
      title:
        "Dreamy AI-generated geometric scenes mesmerize social media users",
      description:
        '"This was the point where AI-generated art passed the Turing Test for me."',
      url: "https://arstechnica.com/?p=1968790",
      source: "arstechnica",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T21:13:13+00:00",
    },
    {
      author: "Christine Hall",
      title:
        "Real estate tech companies continue to get hammered by high mortgage rates",
      description:
        "Once valued at over $2 billion, rent-to-own startup Divvy Homes conducted its third round of layoffs in a year's time.",
      url: "https://techcrunch.com/2023/09/17/real-estate-tech-companies-continue-to-get-hammered-by-high-mortgage-rates/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-17T14:15:44+00:00",
    },
    {
      author: "Sheena Vasani",
      title: "Here are the best Kindle deals right now",
      description:
        "Amazon’s latest Paperwhite is on sale with a power adapter and a&nbsp;fabric cover for $174.97. | Photo by Chaim Gartenberg / The Verge When it comes to finding a device to use to read your ebooks, you have a few options to choose from. You can always buy a tablet or use your phone, but those devices are multipurpose and can be used for a ton of things, like surfing the web or doom-scrolling on Twitter. If you are looking for something to strictly read books, e-readers, while niche, are designed to store all of your books in a virtual library with limited functionality. Amazon, one of the...",
      url: "https://www.theverge.com/21539047/best-amazon-kindle-deals",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T14:53:00+00:00",
    },
    {
      author: "Ingrid Lunden",
      title:
        "Darrow gets served $35M for an AI that parses public documents for class action lawsuit potential",
      description:
        "The U.S. is famous (or infamous) for its litigiousness: the country may not have the highest per capita amount of lawsuits (that&#8217;s Germany), but it has the most of any country overall amid a very active legal industry whose caseload is growing in a market that is worth many tens of billions of dollars. Now, [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/darrow-legal-tech/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T11:00:08+00:00",
    },
    {
      author: "Carrie Andrews",
      title:
        "How deep tech founders can secure early-stage fundraising in a downturn",
      description:
        "Deep tech companies, especially in the early stages in difficult funding environments, should focus first and foremost on closing the deal.",
      url: "https://techcrunch.com/2023/09/19/tips-for-deep-tech-founders-fundraising-in-a-downturn/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T13:00:37+00:00",
    },
    {
      author: "Catherine Shu",
      title: "Reed Jobs on how his venture firm tackles cancer",
      description:
        "Reed Jobs’ new venture firm can change the lives of the estimated 18.1 million diagnosed cancer patents worldwide. Yosemite, Jobs’ fund for cancer-fighting biotech, launched in August with $200 million in funding from investors like MIT, Memorial Sloan Kettering Cancer Center and John Doerr. Jobs first became interested in oncology as a teen after his [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/reed-jobs-on-how-his-venture-firm-tackles-cancer/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T00:39:13+00:00",
    },
    {
      author: "Brian Heater",
      title: "California’s right to repair bill heads to Governor’s desk",
      description:
        "California state Assembly has voted in favor of a right to repair legislation that increases consumer ability to fix devices at home. After winding its way through state legislature, the bill is headed to Governor Gavin Newsom’s desk. Senate Bill 244 isn’t the first right to repair bill passed by a U.S. state – nor [&#8230;]",
      url: "https://techcrunch.com/2023/09/14/californias-right-to-repair-bill-heads-to-governors-desk/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T02:23:26+00:00",
    },
    {
      author: "Manish Singh",
      title: "Meta says not planning ads on WhatsApp",
      description:
        "Meta on Friday disputed a media report that said the social giant was exploring bringing ads on the popular messaging app WhatsApp. This @FT story is false. We aren&#39;t doing this. Also it looks like you misspelled Brian&#39;s name&#8230; https://t.co/Z47z9FC5yu &#8212; Will Cathcart (@wcathcart) September 15, 2023",
      url: "https://techcrunch.com/2023/09/14/meta-says-not-planning-ads-on-whatsapp/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T04:42:04+00:00",
    },
    {
      author: "Manish Singh",
      title: "Prosus, Naspers CEO Bob van Dijk abruptly steps down",
      description:
        "Bob van Dijk, the chief executive of Naspers and Prosus, has stepped down from his position effective immediately, the firms said. Ervin Tu, presently Prosus&#8217; Group Chief Investment Officer, has been promoted as interim chief executive of the firms. “The Boards of Prosus and Naspers want to thank Bob for his leadership over a full [&#8230;]",
      url: "https://techcrunch.com/2023/09/17/prosus-naspers-ceo-bob-van-dijk-abruptly-steps-down/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T05:34:04+00:00",
    },
    {
      author: "Tom Warren",
      title: "Activision was briefed on Nintendo’s Switch 2 last year",
      description:
        "Photo by James Bareham / The Verge Rumors of a Nintendo Switch 2 announcement have grown recently after reports of developer demos at Gamescom last month. Now we know that Activision was briefed on a next-generation Nintendo Switch last year, thanks to internal emails from the FTC v. Microsoft case.Activision executives, including CEO Bobby Kotick, met with Nintendo executives in December 2022 to discuss a next-generation Switch. In an internal email chain, Chris Schnakenberg, head of Activision’s platform strategy and partner relations, prepared a summary of the “Switch NG” (Switch next-...",
      url: "https://www.theverge.com/2023/9/18/23878412/nintendo-switch-2-activision-briefing-next-gen-switch",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T13:06:50+00:00",
    },
    {
      author: "Jacob Kastrenakes",
      title:
        "Apple made it way cheaper to repair an iPhone 15 Pro’s broken back glass",
      description:
        "iPhone 15 Pro and Pro Max. | Photo: Dan Seifert / The Verge It’s significantly cheaper to repair the back glass on an iPhone 15 Pro than it was on the iPhone 14 Pro. Apple posted price estimates for its new phones over the weekend, listing a repair price of $169 for the 15 Pro and $199 for the Pro Max to replace either phone’s shattered back glass.That’s up to a $350 decrease from the repair price for last year’s models. For the iPhone 14 Pro and 14 Pro Max, Apple charged $499 and $549 for back glass replacement — frankly, outlandish prices that ran more expensive than the cost of an...",
      url: "https://www.theverge.com/2023/9/18/23878447/iphone-15-back-glass-repair-price-apple",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T13:27:11+00:00",
    },
    {
      author: "Antonio G. Di Benedetto",
      title:
        "Apple’s new AirPods Pro with USB-C charging case is already $50 off on a preorder",
      description:
        "While this is technically a photo of second-gen AirPods Pro with a Lightning case, the new USB-C model will look identical. | Photo by Chris Welch / The Verge Apple’s biggest announcement last week at its “Wonderlust” event was, without a doubt, the iPhone 15’s change to USB-C, which is already having a ripple effect, as the AirPods Pro are also ditching Lightning for the port upgrade. Now, surprisingly, you can preorder the new second-gen AirPods Pro with USB-C ahead of its September 22nd release date for $199.99 ($50 off) at Best Buy.The AirPods Pro are the first of Apple’s wireless...",
      url: "https://www.theverge.com/2023/9/18/23878472/apple-airpods-pro-usbc-anker-magsafe-charger-cube-samsung-deal-sale",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T15:52:12+00:00",
    },
    {
      author: "Sarah Perez",
      title:
        "News aggregator app SmartNews’ latest feature aims to tackle doomscrolling",
      description:
        "News aggregator SmartNews is today launching a new feature that it hopes will help to combat the anxiety associated with regularly consuming negative news &#8212; something often referred to as &#8220;doomscrolling.&#8221; Instead of encouraging impulsive scrolling through its headlines, the app&#8217;s new feature called SmartTake claims to offer a selection of uplifting stories, editor&#8217;s picks, [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/news-aggregator-app-smartnews-latest-feature-aims-to-tackle-doomscrolling/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T14:29:09+00:00",
    },
    {
      author: "Catherine Shu",
      title:
        "Monoclonal antibody treatments have many challenges — Narval is fixing them",
      description:
        "Monoclonal antibodies are the building blocks of some of the most important medical treatments in the world. But they have limitations. For example, the large size of the molecules mean monoclonal antibody treatments usually need to be injected — even for eye conditions. Narval CEO Jose Luis Nuno describes the first time he saw a [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/narval-monoclonal-antibody-treatments/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:04:41+00:00",
    },
    {
      author: "Frederic Lardinois",
      title:
        "The Unified Acceleration Foundation wants to create an open standard for accelerator programming",
      description:
        "At the Open Source Summit Europe in Bilbao, Spain, the Linux Foundation today announced the launch of the Unified Acceleration (UXL) Foundation. The group&#8217;s mission is to deliver &#8220;an open standard accelerator programming model that simplifies development of performant, cross-platform applications.&#8221; The foundation&#8217;s founding members include the likes of Arm, Fujitsu, Google Cloud, Imagination Technologies, [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/the-unified-acceleration-foundation-wants-to-create-an-open-standard-for-accelerator-programming/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:23:41+00:00",
    },
    {
      author: "Sean Hollister",
      title:
        "Microsoft’s new Xbox controller borrows great ideas from Stadia, Steam, and Sony",
      description:
        "Microsoft’s new core gamepad, codenamed Sebile, may become the new default Xbox gamepad in May 2024. | Image via court documents, text removed by The Verge New Xbox for 2024! New hybrid Xbox for 2028! But can we just appreciate Microsoft’s leaked Sebile controller for a sec? The $70 pad could arrive in 2024 chock-full of the best parts of Sony’s DualSense, Valve’s Steam Controller, Google Stadia, and — here’s hoping — 8BitDo. Image: FTC v. Microsoft “Sebile — The New Xbox Controller.” Obviously, it’s taking the Sony DualSense’s “precision haptic feedback.”Right, here...",
      url: "https://www.theverge.com/2023/9/19/23880809/microsoft-xbox-leak-gamepad-sebile-stadia-steam-sony",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T20:12:49+00:00",
    },
    {
      author: "Emily Mullin",
      title: "Everything We Know About Neuralink's Brain Implant Trial",
      description:
        "Elon Musk’s neurotech startup announced that it is now seeking patients with paralysis to test a brain-computer interface.",
      url: "https://www.wired.com/story/everything-we-know-about-neuralinks-brain-implant-trial/",
      source: "Wired",
      image:
        "https://media.wired.com/photos/650a02e0d7ea654c08913303/master/pass/musk-science-GettyImages-1258889338.jpg",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T20:41:57+00:00",
    },
    {
      author: "Carrie Andrews",
      title:
        "Ask Sophie: Can you explain the H-1B visa, EB-2 green card transfer and Visa Bulletin?",
      description:
        "Here's another edition of “Ask Sophie,” the advice column that answers immigration-related questions about working at technology companies.",
      url: "https://techcrunch.com/2023/09/20/ask-sophie-can-you-explain-the-h-1b-visa-eb-2-green-card-transfer-and-visa-bulletin/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T12:00:46+00:00",
    },
    {
      author: null,
      title: "UpCodes (YC S17) is hiring remote engineers across the Americas",
      description: "Comments",
      url: "https://up.codes/careers",
      source: "Hacker News",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T12:00:44+00:00",
    },
    {
      author: "Sarah Perez",
      title: "Former WarnerMedia CEO Jason Kilar joins Roblox’s board",
      description:
        "Former WarnerMedia CEO Jason Kilar has joined the board of directors at the online gaming platform company Roblox. The appointment, which was effective as of September 13, will see Kilar joining board chairman and Roblox CEO David Baszucki, as well as lead independent director Anthony P. Lee, and board members Gregory Baszucki, Christopher Carvalho, Gina [&#8230;]",
      url: "https://techcrunch.com/2023/09/15/former-warnermedia-ceo-jason-kilar-joins-robloxs-board/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T15:20:57+00:00",
    },
    {
      author: "Andrew Webster",
      title:
        "The Elder Scrolls VI will skip PS5 and isn’t coming until at least 2026",
      description:
        "Image: Bethesda Softworks A document released as part of the FTC v. Microsoft case confirms what was long expected: The Elder Scrolls VI isn’t going to launch for a few years, and it isn’t coming to PlayStation. According to the new chart, which Microsoft produced for the FTC, the next Elder Scrolls game isn’t expected to launch until at least 2026 — something a Microsoft lawyer also mentioned in the court case. And much like Bethesda’s most recent games — Starfield and Redfall — it’ll be available on both PC and Xbox when it does launch.In a statement about exclusivity attached...",
      url: "https://www.theverge.com/2023/9/18/23878504/the-elder-scrolls-6-2026-release-xbox-exclusive",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T13:40:45+00:00",
    },
    {
      author: "Emma Roth",
      title: "Windows leader Panos Panay is leaving Microsoft",
      description:
        "Panos Panay | Photo by Becca Farsace / The Verge Panos Panay, the chief product officer at Microsoft leading Windows development and the company’s Surface line, is leaving Microsoft. In an announcement on Monday, Microsoft told employees: “After nearly 20 years at the company, Panos Panay has decided to leave Microsoft.”Panay first joined Microsoft in 2004 as a group program manager. After overseeing the company’s Surface line, Panay became the company’s chief product officer in 2018, where he led the development of Windows 11.You can read the full email to employees below:Team, After...",
      url: "https://www.theverge.com/2023/9/18/23878609/microsoft-windows-panos-panay-leaving",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T14:18:36+00:00",
    },
    {
      author: "Jacquelyn Melinek",
      title: "Blockchain Capital launches two new funds for a total of $580M",
      description:
        "The crypto bear market may be ongoing, but Blockchain Capital is still going big. It closed two new funds for a total of $580 million, the firm’s general partner Spencer Bogart told TechCrunch. The two venture funds, its sixth early-stage fund and its first “opportunity fund,” are allocated roughly two-thirds and one-third of the $580 [&#8230;]",
      url: "https://techcrunch.com/2023/09/18/blockchain-capital-launches-two-new-funds-for-a-total-of-580m/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T15:00:57+00:00",
    },
    {
      author: "Aria Alamalhodaei",
      title:
        "Stoke Space completes milestone test in quest to build a fully reusable rocket",
      description:
        "Stoke Space, a startup that’s taking an unconventional approach to rocket design, successfully completed a key test of its second stage prototype, bringing the company one step closer to flying a fully reusable launch vehicle. The prototype, called “Hopper2,” executed a 15-second test flight during which the vehicle flew to a height of around 30 [&#8230;]",
      url: "https://techcrunch.com/2023/09/18/stoke-space-completes-milestone-test-in-quest-to-build-a-fully-reusable-rocket/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T17:20:15+00:00",
    },
    {
      author: "Ash Parrish",
      title: "Unity plans to change its disastrous new pricing program",
      description:
        "Image: Unity Unity plans to change its forthcoming pay-per-install program following widespread criticism from game developers.“We apologize for the confusion and angst the runtime fee policy we announced on Tuesday caused,” Unity posted on X (formerly Twitter). “We are listening, talking to our team members, community, customers, and partners, and will be making changes to the policy. We will share an update in a couple of days.”This new communication from Unity comes after nearly a week of clarifications, retractions, and a growing force of upset developers who threaten not only to...",
      url: "https://www.theverge.com/2023/9/18/23879029/unity-pricing-model-change",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T18:57:19+00:00",
    },
    {
      author: "Carly Page",
      title: "UK police officers’ data stolen in cyberattack on ID supplier",
      description:
        "The personal details of thousands of U.K. police officers have been stolen after a suspected ransomware attack on a third-party supplier. Greater Manchester Police, one of the largest police departments in the U.K., confirmed last week that the supplier, since confirmed as Stockport based identity card maker Digital ID, holds “some information on those employed [&#8230;]",
      url: "https://techcrunch.com/2023/09/18/uk-police-officers-data-stolen-cyberattack-digital-id/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T18:55:46+00:00",
    },
    {
      author: "Wes Davis",
      title:
        "TMNT: Mutant Mayhem starts streaming on Paramount Plus on September 19th",
      description:
        "Mutant Mayhem comes to Paramount Plus on September 19th. | Image: Paramount Paramount announced that Teenage Mutant Ninja Turtles: Mutant Mayhem will hit Paramount Plus tomorrow in the US and Canada. The CG-animated movie is now the seventh Turtles movie in a line that started with the better-than-it-should’ve-been 1990 live-action film. Mutant Mayhem is already available to preorder on 4K UHD Blu-ray, standard Blu-ray, and DVD.The movie hits just a day before Paramount Plus ends its 50 percent discount for a year of its ad-supported tier ($29.99) or a year of its Paramount Plus with Showtime...",
      url: "https://www.theverge.com/2023/9/18/23879336/teenage-mutant-ninja-turtles-mutant-mayhem-streaming-paramount-plus-release",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T20:36:38+00:00",
    },
    {
      author: "Aria Alamalhodaei",
      title: "Max Q: Firefly conquered the night",
      description:
        "In this issue: Firefly Aerospace conquered the night, news from Varda Space and more",
      url: "https://techcrunch.com/2023/09/18/max-q-firefly-conquered-the-night/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T22:00:15+00:00",
    },
    {
      author: "Jennifer Pattison Tuohy",
      title: "The Fire TV should be at the heart of Amazon’s smart home",
      description:
        "Symbiosis between its Fire TVs and its Alexa smart home ambitions could help Amazon create a smart home that works for everyone. | Photo by Chris Welch / The Verge Amazon’s fall hardware event is taking place this week, and the company will undoubtedly be searching for its next big hardware hit. But how about making its existing hardware (and software) better? Continue reading&hellip;",
      url: "https://www.theverge.com/2023/9/19/23880495/amazon-fire-tv-alexa-smart-home-hardware-event",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:30:00+00:00",
    },
    {
      author: "Alex Wilhelm",
      title:
        "Instacart’s IPO storms out the gate, showing that unicorns can, in fact, go public and survive",
      description:
        "For startups dying of thirst in this desert devoid of capital, Instacart could not have offered up a more satisfying glass of cool water.",
      url: "https://techcrunch.com/2023/09/19/instacarts-ipo-storms-out-the-gate-showing-that-unicorns-can-in-fact-go-public-and-survive/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:54:40+00:00",
    },
    {
      author: "Taylor Hatmaker",
      title:
        "Nolej’s AI-generated classroom tools are a force multiplier for educators",
      description:
        "The idea of bringing AI into the classroom doesn’t sit well with everyone, but the team behind Nolej believes that generative AI can supercharge learning — all while keeping teachers front and center. Nolej AI is an AI-powered tool that lets educators quickly generate interactive learning modules like quizzes, flashcards, games and interactive videos. “We [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/nolejs-ai-generated-classroom-tools-are-a-force-multiplier-for-educators/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T20:52:16+00:00",
    },
    {
      author: "Kevin Purdy",
      title:
        "Wizardry remaster keeps Apple II vibes but adds graphics and modern graces",
      description:
        "Digital Eclipse gives a new generation the best possible door to the dungeon.",
      url: "https://arstechnica.com/?p=1968668",
      source: "Ars Technica",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T17:40:39+00:00",
    },
    {
      author: "Emma Roth",
      title:
        "The iPhone 15 Pro’s 5G modem reportedly boosts speeds by up to 24 percent",
      description:
        "Photo by Nilay Patel / The Verge The iPhone 15 Pro could come with better 5G connectivity. That’s according to data from SpeedSmart (via 9to5Mac), which indicates that the iPhone 15 Pro will offer up to 24 percent faster download 5G speeds when compared to its iPhone 14 Pro predecessor.As shown by the data from SpeedSmart, the biggest jump occurred on Verizon’s network, which showed an average download speed of 195.83Mbps on the iPhone 14 Pro, as opposed to 243.06Mbps on the iPhone 15 Pro. Meanwhile, the iPhone 15 Pro on T-Mobile had the fastest average 5G download speeds at 300.92Mbps, as...",
      url: "https://www.theverge.com/2023/9/15/23875787/iphone-15-pro-better-5g-connectivity",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-15T22:30:31+00:00",
    },
    {
      author: "Emma Roth",
      title:
        "Google’s Bard chatbot can now find answers in your Gmail, Docs, Drive",
      description:
        "Image: Google Google’s Bard AI chatbot is no longer limited to pulling answers from just the web — it can now scan your Gmail, Docs, and Drive to help you find the information you’re looking for. With the new integration, you can ask Bard to do things like find and summarize the contents of an email or even highlight the most important points of a document you have stored in Drive.There’s a whole range of use cases for these integrations, which Google calls extensions, but they should save you from having to sift through a mountain of emails or documents to find a particular piece of...",
      url: "https://www.theverge.com/2023/9/19/23878999/google-bard-ai-chatbot-gmail-docs-drive-extensions",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T10:01:00+00:00",
    },
    {
      author: "Aria Alamalhodaei",
      title: "Rocket Lab’s Electron suffers first failure in over two years",
      description:
        "Rocket Lab’s 41st Electron mission on behalf of customer Capella Space ended in failure early Tuesday, with issues abruptly appearing after stage separation around 2-and-a-half minutes after launch. The live video feed of the rocket stopped working shortly after the second stage ignited its engine. Around 45 seconds after stage separation, the launch director declared, [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/rocket-labs-electron-suffers-first-failure-in-over-two-years/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T13:51:30+00:00",
    },
    {
      author: "Sarah Fielding",
      title: "Apple's 12.9-inch iPad Pro drops to $999",
      description:
        "The 12.9-inch Apple iPad Pro's cost has finally dropped into the triple digits. The 128GB sixth-generation model is at an all-time low price of $999 (hey, $1 under $1,000 still counts) from $1,099 — a nine percent discount. The deal is only available in Space Gray, with the Silver model coming in at $1,049.&nbsp;Apple's sixth-gen iPad Pro 12.9-inch came on the scene in 2022, and — though it wasn't a major upgrade — it garnered an 87 in our review. The biggest change was a swap from the M1 to the M2 chip, which increased its GPU performance by 52 percent to a score of 32,834. The M2 chip...",
      url: "https://www.engadget.com/apples-129-inch-ipad-pro-drops-to-999-143633282.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2022-11/bf495040-59e1-11ed-a74d-0924f57e9b11",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T14:36:33+00:00",
    },
    {
      author: "Steve Lohr",
      title:
        "A Key Question in Google’s Trial: How Formidable Is Its Data Advantage?",
      description:
        "The government states that data is “oxygen for a search engine” and that Google’s anticompetitive behavior has given it a data fortress. Google says innovation explains its success.",
      url: "https://www.nytimes.com/2023/09/18/business/google-antitrust-trial-data.html",
      source: "The New York Times",
      image:
        "https://static01.nyt.com/images/2023/09/19/multimedia/00JPgoogle-antitrust-data-print-zqmf/00google-antitrust-data-dintzer-zqmf-moth-v3.jpg",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T15:21:11+00:00",
    },
    {
      author: "Romain Dillet",
      title: "BioticsAI wants to improve prenatal ultrasound scans with AI",
      description:
        "Meet BioticsAI, a startup that has built an AI-based platform that plugs into an ultrasound machine to prevent fetal malformation misdiagnosis. BioticsAI has been quietly working on its solution for the past two years and is now unveiling its product onstage at TechCrunch Disrupt as part of the Startup Battlefield. “BioticsAI processes all of the [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/bioticsai-wants-to-improve-prenatal-ultrasound-scans-with-ai/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:31:27+00:00",
    },
    {
      author: "Kyle Wiggers",
      title:
        "OpenAI launches a red teaming network to make its models more robust",
      description:
        "In its ongoing effort to make its AI systems more robust, OpenAI today launched the OpenAI Red Teaming Network, a contracted group of experts to help inform the company&#8217;s AI model risk assessment and mitigation strategies. Red teaming is becoming an increasingly key step in the AI model development process as AI technologies, particularly generative [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/openai-launches-a-red-teaming-network-to-make-its-models-more-robust/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:38:38+00:00",
    },
    {
      author: "Benj Edwards",
      title:
        "Google’s AI assistant can now read your emails, plan trips, “double-check” answers",
      description:
        "Google admits that Bard isn't always accurate; ropes in Gmail through new Extensions.",
      url: "https://arstechnica.com/?p=1969226",
      source: "Ars Technica",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T17:35:30+00:00",
    },
    {
      author: "Antonio G. Di Benedetto",
      title:
        "Nikon’s new ZF is a retro-styled full-frame camera aimed right at our nostalgic hearts",
      description:
        "The Nikon ZF is the company’s latest camera. | Photo by Becca Farsace / The Verge After nine years of occasionally chasing the retro-camera-with-modern-features unicorn, Nikon may have finally gotten the formula right. The Japanese camera maker is announcing the Nikon ZF, a modern mirrorless camera packed with fairly high specs — like a 24.5-megapixel full-frame sensor, 299-point tracking autofocus with subject detection, in-body image stabilization, and dual card slots (of a sort) — in a body that looks just like one of the camera’s analog forebears. Nikon may have done this dance...",
      url: "https://www.theverge.com/2023/9/20/23878641/nikon-zf-full-frame-mirrorless-classic-camera-fm2-film-specs-price",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T04:00:00+00:00",
    },
    {
      author: null,
      title:
        "Lantern (YC W24) – Hiring Engineers to Build PostgreSQL Vector Database for AI",
      description: "Comments",
      url: "https://lantern-db.notion.site/lantern-db/Lantern-is-hiring-Core-Database-Engineers-396a612dcfdb4c9eb274670680c8d8b5",
      source: "Hacker News",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-16T21:00:56+00:00",
    },
    {
      author: "David Pierce",
      title:
        "We tried to make a hit song with only AI tools — and it got messy",
      description:
        "Illustration by Samar Haddad / The Verge With only a couple of minutes and access to YouTube, you can now make SpongeBob SquarePants sing your favorite Taylor Swift song. Or make Taylor Swift sing your favorite Drake song. Or make Drake sing your song. AI covers and AI-generated originals are suddenly everywhere on the internet, to the point where even diehard fans don’t know what’s a real leak and what’s a generated one. It’s a complicated ethical and legal mess and makes being a music fan weirder than ever.That’s only the very beginning of the ways AI is coming into the music-making...",
      url: "https://www.theverge.com/23878445/ai-music-tools-magenta-suno-chatgpt-vergecast",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T13:47:06+00:00",
    },
    {
      author: "Morgan Sung",
      title:
        "Vivek Ramaswamy is in his TikTok era, with Jake Paul’s endorsement",
      description:
        "Vivek Ramaswamy is on TikTok now, thanks to Jake Paul. In the week since he joined the platform, Ramaswamy has amassed about 33,000 followers, secured an endorsement from one of the most polarizing creators in YouTube history and attempted to establish himself as the millennial politician who&#8217;s cool enough to use TikTok but anti-woke enough [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/vivek-ramaswamy-attempts-tiktok-fame-jake-paul/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T23:45:25+00:00",
    },
    {
      author: "Ingrid Lunden",
      title:
        "After relaunching as a studio for creators, LimeWire acquires BlueWillow, a Midjourney competitor",
      description:
        "In the Wild West of generative AI, a new, unlikely cowboy is riding into town. LimeWire &#8212; once infamous for music piracy and incurring the wrath of the music industry before shutting down &#8212; last year pivoted under new owners into the world of content creation. Now, to build that out further, today it&#8217;s announcing [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/limewire-bluewillow/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T06:43:14+00:00",
    },
    {
      author: "Tage Kene-Okafor",
      title:
        "Ghana’s Complete Farmer, which connects farmers to global food buyers, raises $10.4M",
      description:
        "Africa’s agricultural sector has a significant social and economic impact, per McKinsey. The percentage of smallholder farmers in sub-Saharan Africa exceeds 60%, while agriculture accounts for approximately 23% of the region’s gross domestic product. But despite the apparent opportunity in the agricultural sector, it is difficult for Africa to successfully participate in global supply chains [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/ghanas-complete-farmer-which-connects-farmers-to-global-food-buyers-raises-10-4m/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T08:12:05+00:00",
    },
    {
      author: "Aria Alamalhodaei",
      title:
        "Joby Aviation selects Dayton, Ohio for first scaled electric air taxi factory",
      description:
        "Joby Aviation has selected Dayton, Ohio, as the new site for its first scaled electric aircraft factory, with the company preparing to invest up to $500 million in the new site as it looks to start selling air taxi rides as soon as 2025. Today’s announcement puts to rest months of speculation on the location [&#8230;]",
      url: "https://techcrunch.com/2023/09/18/joby-aviation-selects-dayton-ohio-for-first-scaled-electric-air-taxi-factory/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T14:35:49+00:00",
    },
    {
      author: "Lorenzo Franceschi-Bicchierai",
      title:
        "One of the FBI’s most wanted hackers is trolling the U.S. government",
      description:
        "Earlier this year, the U.S. government indicted Russian hacker Mikhail Matveev, also known by his online monikers “Wazawaka” and “Boriselcin,” accusing him of being “a prolific ransomware affiliate” who carried out “significant attacks” against companies and critical infrastructure in the U.S. and elsewhere. The feds also accused him of being a “central figure” in the [&#8230;]",
      url: "https://techcrunch.com/2023/09/18/fbi-most-wanted-hacker-trolling-the-u-s-government/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-18T19:06:17+00:00",
    },
    {
      author: "Devin Coldewey",
      title:
        "Project Gutenberg puts 5,000 audiobooks online for free using synthetic speech",
      description:
        "Open book repository Project Gutenberg has turned thousands of its titles into audiobooks practically overnight using synthetic speech, available now for download or streaming on multiple services. The selection is a bit idiosyncratic (as indeed the archive&#8217;s is generally) but it is nevertheless a powerful demonstration of accessibility in literature. Making an audiobook via traditional [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/project-gutenberg-puts-5000-audiobooks-online-for-free-using-synthetic-speech/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T16:36:51+00:00",
    },
    {
      author: "Kyle Wiggers",
      title: "Allie wants to layer intelligence on top of factory floors",
      description:
        "Factory downtime is an expensive problem. According to one estimate, it costs enterprise companies 11% of their yearly turnover, amounting to almost $1.5 trillion each year. That works out to about $129 million per facility among Fortune 500 companies, over double what Fortune 500 companies reported paying in downtime in 2020. Part of the reason [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/allie-wants-to-layer-intelligence-on-top-of-factory-floors/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T19:48:33+00:00",
    },
    {
      author: "Rita Liao",
      title:
        "US finds no evidence Huawei can mass produce advanced phone chips",
      description:
        "The ability of Huawei &#8212; and China at large &#8212; to manufacture advanced chips amid U.S. sanctions has again come into question as conflicting claims arise. The U.S. finds no evidence that the Chinese smartphone and telecom giant Huawei can produce smartphones with advanced semiconductors at scale, U.S. Commerce Secretary Gina Raimondo said on Tuesday. [&#8230;]",
      url: "https://techcrunch.com/2023/09/19/us-finds-no-evidence-huawei-can-mass-produce-advanced-phone-chips/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-19T23:15:49+00:00",
    },
    {
      author: "Sarah Perez",
      title:
        "Orion, from makers of Halide, lets you use an iPad as an external HDMI display",
      description:
        "Lux, the makers of popular iPhone photography apps like Halide, Spectre and Skylight, is out today with its latest app: Orion, an app that turns an iPad into an external HDMI display for any camera, video game console, or even VHS. The new app is a bit of an offshoot for Lux, which primarily focuses [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/orion-from-makers-of-halide-lets-you-use-an-ipad-as-an-external-hdmi-display/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T17:23:48+00:00",
    },
    {
      author: "Will Shanklin",
      title:
        "Everything Amazon announced at its 2023 Devices and Services event",
      description:
        "Amazon’s fall hardware event was chock full of updates. Perhaps unsurprisingly, given the generative AI boom from the last year, the company began transforming Alexa into a much more versatile and conversational personal chatbot. But it also had plenty of new hardware to introduce, with new models of the Echo Show, security cameras, Echo Frames, a 10-gigabit router and more. Here’s everything Amazon unveiled on Wednesday.Alexa with generative AIAmazonAs generative AI has exploded in popularity during the last year, task-focused personal assistants like Siri, Google Assistant and Alexa now...",
      url: "https://www.engadget.com/everything-amazon-announced-at-its-2023-devices-and-services-event-194621706.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/2c959ea0-57ee-11ee-af7f-c6b135463147",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T19:46:21+00:00",
    },
    {
      author: "Lawrence Bonk",
      title: "Microsoft’s latest Windows 11 update drops on September 26",
      description:
        "Microsoft is releasing a big Windows 11 update next week, on September 26. The catchily-named 23H2 is packed with some real game changing features, along with a whole bunch of quality of life improvements. The update arrives just in time for the launch of the just-announced Surface Laptop Go 3 and the Surface Laptop Studio 2.The big news here is the inclusion of the new AI-powered Windows Copilot feature. This toolset already exists as part of the Edge browser, but now it’ll be natively implemented in Windows, which allows for some nifty use cases. This native implementation means that...",
      url: "https://www.engadget.com/microsofts-latest-windows-11-update-drops-on-september-26-163553126.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/b66fd640-5898-11ee-8fa0-10f99205aafe",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T16:35:53+00:00",
    },
    {
      author: "Jay Peters",
      title: "Threads might be getting an edit button soon",
      description:
        "Illustration: The Verge Meta’s in-development edit button for Threads might let you edit posts within five minutes of publishing them, as reported by developer Alessandro Paluzzi on X (formerly Twitter). Instagram chief Adam Mosseri confirmed shortly after the app’s July launch that an edit button was on the list of potential features, and now that Paluzzi has discovered some details about it, perhaps the feature will be available more widely sometime soon. #Threads is working on the ability to edit posts within 5 minutes pic.twitter.com/TlyoieQNcM— Alessandro Paluzzi (@alex193a...",
      url: "https://www.theverge.com/2023/9/21/23884466/threads-edit-button-development-instagram-meta",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T20:15:35+00:00",
    },
    {
      author: "Kate Park",
      title:
        "HME Square aims to measure glucose painlessly with photoacoustics",
      description:
        "People with diabetes have to monitor their blood sugar levels regularly by pricking their skin. Many glucose-monitoring device makers worldwide are pursuing needle-free approaches to make this painful process more manageable. Among them is a South Korean company called HME Square, which uses photoacoustics to test glucose levels noninvasively. HME Square was founded in 2020 [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/hme-square-aims-to-measure-glucose-painlessly-with-photoacoustics/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T01:24:33+00:00",
    },
    {
      author: "Paul Sawers",
      title:
        "Google expands its subsea cable infrastructure with Nuvem, connecting the U.S., Bermuda, and Portuga",
      description:
        "Google has announced another subsea cable system, as the internet giant strives to bolster its internet infrastructure and get more people using its array of cloud-based services. Dubbed &#8220;Nuvem,&#8221; the new cable represents one of more than a dozen cables that Google has invested in through the years, starting with Unity which went into operation [&#8230;]",
      url: "https://techcrunch.com/2023/09/25/google-nuvem-subsea-cable/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-25T11:26:32+00:00",
    },
    {
      author: "Cade Metz",
      title: "The Secret Ingredient of ChatGPT Is Human Advice",
      description:
        "Companies like OpenAI hone their bots using hand-tailored examples from well-educated workers. But is this always for the best?",
      url: "https://www.nytimes.com/2023/09/25/technology/chatgpt-rlhf-human-tutors.html",
      source: "The New York Times",
      image:
        "https://static01.nyt.com/images/2023/09/14/multimedia/chatbot-secret-sauce-01-bcfl/chatbot-secret-sauce-01-bcfl-moth.jpg",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-25T12:00:16+00:00",
    },
    {
      author: "Jay Peters",
      title:
        "Ring’s new Stick Up Cam Pro includes radar sensors to help with motion detection",
      description:
        "Image: Amazon Amazon just announced the Ring Stick Up Cam Pro at its September 2023 event, and the big new feature is the addition of radar sensors that will help with detecting motion. Amazon says in a press release that the radar sensors will help the camera “measure the distance of an object in its field of view.” With that improved sensing, you’ll be able to set more specific areas for the Stick Up Cam Pro to watch for motion, which could be useful if you want your security camera to keep an eye on a specific spot in your yard.The Stick Up Cam Pro also includes Ring’s “Audio Plus...",
      url: "https://www.theverge.com/2023/9/20/23882430/ring-stick-up-cam-pro-radar-sensors-motion-detection",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T16:24:51+00:00",
    },
    {
      author: "Allison Johnson",
      title: "The new FineWoven iPhone cases are very bad",
      description:
        "This is not good. | Photo by Allison Johnson / The Verge Folks, what you’ve heard so far is true. Apple’s new FineWoven iPhone cases and accessories are bad. Like, really bad. I’ve been puzzling over them for the past week, looking at them from different angles. Picking them up, setting them down, petting them. Seven days later, I still can’t make sense of them and have no other choice but to say it out loud: FineWoven is very bad.FineWoven is a new fabric option you’ll find on iPhone 15 cases, AirTag holders, and MagSafe wallets. Apple calls it a “luxurious and durable microtwill...",
      url: "https://www.theverge.com/2023/9/20/23882255/apple-iphone-15-finewoven-case-wallet-bad",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T17:50:41+00:00",
    },
    {
      author: "Romain Dillet",
      title:
        "Front goes beyond the unified inbox with a Zendesk-style knowledge base",
      description:
        "Customer operations platform Front is better known for its omnichannel inbox that lets you aggregate all customer conversations in a single view — emails, chat conversations, SMS, social media messages. Today, the company unveiled a handful of new features that turns Front into a more complete customer support platform. By bringing all these features under [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/front-goes-beyond-the-unified-inbox-with-a-zendesk-style-knowledge-base/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T18:43:49+00:00",
    },
    {
      author: "Lauren Forristal",
      title:
        "Former Meta AI VP debuts Sizzle, an AI-powered learning app and chatbot",
      description:
        "Founded by the former vice president of AI at Meta, Jerome Pesenti, Sizzle is a free AI-powered learning app that generates step-by-step answers to math equations and word problems. The company recently launched four new features, including a grading capability, a feature that regenerates steps, an option to see multiple answers to one problem and [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/former-meta-ai-vp-debuts-sizzle-an-ai-powered-learning-app-and-chatbot/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T20:22:42+00:00",
    },
    {
      author: "Paul Sawers",
      title:
        "AppFactor drags legacy enterprise apps to the cloud through automation",
      description:
        "Technical debt is often the unsung villain of the enterprise, crippling companies seeking to modernize as they realize just how much &#8220;legacy&#8221; lives in their stack. And as with most kinds of debt, there is usually interest to pay, too. This is something that fledgling U.K. startup AppFactor is setting out to solve, with a [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/appfactor-drags-legacy-enterprise-apps-to-the-cloud-through-automation/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T20:47:51+00:00",
    },
    {
      author: "Jennifer Pattison Tuohy",
      title: "You can finally ask Siri to play Spotify on a HomePod",
      description:
        "Siri can now play your Spotify playlists on your HomePod. | Photo by Chris Welch / The Verge A new feature in iOS 17 finally sets Spotify free — allowing you to use the voice assistant to start your Spotify session directly on your HomePod, hands-free. The capability (spotted by 9to5Mac) allows you to start an AirPlay session from your phone using a Siri command. So now you can say, “Hey Siri, play The National on Spotify” to your HomePod, and Siri will route the command through your phone and start streaming Spotify on the smart speaker.It’s a workaround, but it works. When The Verge...",
      url: "https://www.theverge.com/2023/9/21/23883860/siri-can-now-play-spotify-on-apple-homepod-smart-speaker",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T15:36:27+00:00",
    },
    {
      author: "Brian Heater",
      title: "Diligent raises $25 million to triple its nursing robot’s reach",
      description:
        "The pandemic had a profound impact on countless careers, but few jobs were hit quite like nursing. As hospitals overflowed, staff was forced to take on impossible long shifts, risking their own health in the process. In many ways, it was the perfect environment to introduce a robot like Diligent’s Moxi, a system designed to [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/diligent-raises-25-million-to-triple-its-nursing-robots-reach/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T18:00:50+00:00",
    },
    {
      author: "Kyle Wiggers",
      title: "Secoda secures $16M to expand its data cataloging platform",
      description:
        "Secoda, a startup developing what it describes as an AI-powered data search and cataloging platform, today announced that it raised $16 million in a funding round led by Craft Ventures with participation from Abstract Ventures and several angel investors. Bringing Secoda&#8217;s total raised to $18.3 million, Secoda co-founder and CEO Etai Mizrahi said that the [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/secoda-secures-16m-to-expand-its-data-cataloging-platform/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T18:00:40+00:00",
    },
    {
      author: "Brian Heater",
      title:
        "Firebot is designed to scout burning builders before sending in firefighters",
      description:
        "Stanley Wilson died a decade ago, battling a six-alarm fire at a Dallas, Texas, condominium complex. Two additional firefighters were taken to a hospital and two residents were treated on site for smoke inhalation, but all survived. A pair of reports were made public the following year, citing issues with training and risk assessment, among [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/firebot-is-designed-to-scout-burning-builders-before-sending-in-firefighters/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T18:27:40+00:00",
    },
    {
      author: "Umar Shakir",
      title: "Samsung leaks its new Fan Edition phone, tablet, and earbuds",
      description:
        "Well, that certainly looks like a new set of Fan Edition hardware. | Image: Samsung Samsung has leaked its own latest “Fan Edition” product lineup that includes the new Galaxy Buds FE earbuds, Galaxy S23 FE smartphone, and Galaxy Tab S9 FE tablet. The new products have come to light via the company’s Argentinian website, where a product page for the new earbuds has seemingly launched prematurely — and includes photos of the rest of the lineup (via SamMobile).Another image references an October 4th date (with the clock at 12:45), which might indicate the release or announcement date for...",
      url: "https://www.theverge.com/2023/9/22/23885350/samsung-leaks-fan-edition-galaxy-buds-s23-tab-fe",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T15:07:11+00:00",
    },
    {
      author: "Ash Parrish",
      title: "Unity announces its revamped pricing model",
      description:
        "Illustration by Cath Virginia / The Verge A little more than a week after announcing a disastrous new pricing model that infuriated developers, Unity has introduced its revamped version. The new plan is a drastic departure from what was initially announced. Now, users on the Unity Personal subscription plan will not be charged the new fee, and Unity will increase the revenue cap on games made with that plan to $200,000.Furthermore, any game made with Unity that makes less than $1 million in 12 months will not be subject to the fee.The company is also changing what games can be assessed with the...",
      url: "https://www.theverge.com/2023/9/22/23882768/unity-new-pricing-model-update",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T17:51:08+00:00",
    },
    {
      author: "Malak Saleh",
      title:
        "NASA's OSIRIS-REx successfully delivers asteroid samples back to Earth",
      description:
        "NASA’s OSIRIS-REx seven-year mission to collect rocks and dust from a near-Earth asteroid is complete. The capsule containing the final samples returned to Earth on the morning of September 24th, touching down in the desert at the Department of Defense’s Utah Test and Training Range at 10:52 am ET.The device collected around 250 grams of material from a carbon-rich asteroid dubbed “Bennu,” which NASA says hosts some of the oldest rocks in our solar system. The sample gives scientists more information about the building blocks of what planetary makeup looked like 4.5 billion years ago.&...",
      url: "https://www.engadget.com/nasas-osiris-rex-successfully-delivers-asteroid-samples-back-to-earth-091107901.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/bf2e6ba0-5af2-11ee-bfbe-fa87dadf0c1b",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-25T09:11:07+00:00",
    },
    {
      author: "Jon Porter",
      title:
        "Pixel 8 series rumored to include seven years of software support",
      description:
        "A teaser image of the Pixel 8 and 8 Pro released by Google. | Image: Google Google’s upcoming Pixel 8 and Pixel 8 Pro could come with seven years of software support, according to a leaked list of specs published by 91Mobiles. Kamila Wojciechowska, the original source of the leak, has also published US pricing for the two unannounced phones ahead of their October 4th launch. The Pixel 8 Pro is reportedly due to start at $899, the same as the 7 Pro, while the Pixel 8 could start at $699, a $100 increase over the $599 starting price for the Pixel 7.Wojciechowska notes that it’s unclear...",
      url: "https://www.theverge.com/2023/9/25/23888831/pixel-8-pro-seven-years-software-support-price-rumors-leak",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-25T09:10:49+00:00",
    },
    {
      author: "Emma Roth",
      title: "All the news from Amazon’s September 2023 product launch event",
      description:
        "Illustration by Alex Castro / The Verge Amazon’s big fall product event comes from a smaller company and with big AI expectations. Continue reading&hellip;",
      url: "https://www.theverge.com/2023/9/20/23881164/amazon-event-hardware-devices-alexa-echo-ring",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T16:06:20+00:00",
    },
    {
      author: "Alex Wilhelm",
      title:
        "Klaviyo’s strong IPO pricing should give unicorns an idea of what they are worth",
      description:
        "Defending — or nearly defending — a 2021-era valuation in a 2023 IPO is impressive, given how much the value of tech companies has changed in the past year and a half.",
      url: "https://techcrunch.com/2023/09/20/klaviyos-ipo-pricing-analysis/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T17:03:17+00:00",
    },
    {
      author: "Alex Cranz",
      title: "Amazon Fire TV Soundbar hands-on: it’s loud and inexpensive",
      description:
        "Yup, that’s a soundbar. | Photo by Alex Cranz / The Verge Soundbars are tricky. They need to be big enough that they sound better than the dinky speakers on your TV, but they need to be cheap enough that you don’t balk at upgrading your sound after just spending a lot of money on a TV. I didn’t get to spend enough time with Amazon’s $119.99 Fire TV Soundbar, but I can confirm it sounds bigger than it looks.What I didn’t hear was a lot of detail. Voices rumble with appropriate amounts of bass — but in the very audio-unfriendly environment we listened to the soundbar in, dialogue was...",
      url: "https://www.theverge.com/23882491/amazon-fire-tv-soundbar-hands-on-price",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T17:30:53+00:00",
    },
    {
      author: "Mary Ann Azevedo",
      title: "Why is Y Combinator so defensive lately?",
      description:
        "Y Combinator has been on the defense as of late. This past weekend, leaders from the popular accelerator were vocal on X (formerly known as Twitter) in their reaction to a comment made by the CEO of another accelerator at an event. Ali Partovi, who founded Neo in 2017, was the keynote speaker at HackMIT [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/why-is-y-combinator-so-defensive-lately/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T20:58:32+00:00",
    },
    {
      author: "Sarah Perez",
      title:
        "YouTube to add AI creator tools to find music for videos, add dubs",
      description:
        "YouTube is expanding its Creator Music Studio, announced last year, with new AI features in addition to the launch of an AI-dubbing tool. Currently, creators can use the Creator Music Studio to search for songs, a specific artist, or a music genre they want to use in a video. Now, they&#8217;ll be able to leverage [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/youtube-to-add-ai-creator-tools-to-find-music-for-videos-add-dubs/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T14:39:25+00:00",
    },
    {
      author: "Emilia David",
      title: "Microsoft to add DALL-E 3 to Bing Chat",
      description:
        "Image: Microsoft Microsoft announced it will soon add access to OpenAI’s DALL-E 3 image generator for users to create images right in a chat.DALL-E 3, which will be released for ChatGPT’s enterprise users in October, will allow people to type a couple of sentences to create a photo. Microsoft did not specify when DALL-E 3 on Bing will come out. The company also added new shopping features to Bing. Bing can ask users specific questions on how a product will be used or other more personalized questions so people can pinpoint the right product that suits their needs. Bing also lets people find...",
      url: "https://www.theverge.com/2023/9/21/23873690/microsoft-new-ai-features-bing-search-shopping-dall-e-3",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T14:52:05+00:00",
    },
    {
      author: "Kris Holt",
      title: "The Surface Laptop Go 3 starts at $799 and arrives on October 3",
      description:
        "Microsoft unveiled the Surface Laptop Go 3 during its Surface event on Thursday. The company says the latest model will run for up to to 15 hours on a single charge and that it will be ultra thin and ultra light (at under 2.5 pounds).&nbsp;It has a 12.4-inch touchscreen and a fingerprint power button. At first glance, the bezel doesn&#39;t seem to have changed much from previous iterations. Performance-wise, Microsoft claims the Surface Laptop Go 3 is 88 percent faster than the original model, which arrived three years ago.Unsurprisingly, given Microsoft&#39;s focus on AI over the last year...",
      url: "https://www.engadget.com/the-surface-laptop-go-3-starts-at-799-and-arrives-on-october-3-150707089.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/460ee420-5890-11ee-8faf-06c12988ad10",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T15:07:07+00:00",
    },
    {
      author: "Natasha Lomas",
      title: "UK bolts US ‘data bridge’ deal onto EU-US Data Privacy Framework",
      description:
        "The UK government has officially confirmed it will piggyback on a transatlantic data transfer deal between the European Union and the US by bolting on an extension which it&#8217;s dubbed the &#8220;UK-US data bridge&#8221;. Back in June the UK and US reached an agreement in principle over this arrangement. Today the UK government confirmed that [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/uk-us-data-bridge/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T16:43:04+00:00",
    },
    {
      author: "Walter Thompson",
      title:
        "TechCrunch+ Roundup: Prompt engineering, web3 gaming survey, how to spend $10K on paid ads",
      description:
        "TechCrunch Disrupt 2023 ended yesterday, and out of all the events I've attended since working here, this one was my favorite.",
      url: "https://techcrunch.com/2023/09/22/techcrunch-roundup-prompt-engineering-web3-gaming-survey-how-to-spend-10k-on-paid-ads/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T17:55:07+00:00",
    },
    {
      author: "Tim De Chant",
      title:
        "LimeLoop’s sleek reusable mailers seek to replace cardboard boxes",
      description:
        "The startup’s smart mailers are reusable dozens of times, reducing the carbon footprint by 90% compared with cardboard boxes.",
      url: "https://techcrunch.com/2023/09/22/lime-loop-reusable-packaging/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T21:33:08+00:00",
    },
    {
      author: "Rebecca Szkutak",
      title:
        "Building an equitable cap table puts more tools in a startup’s toolbox",
      description:
        "Building an equitable cap table allows startups to bring on experts they wouldn't be able to hire while making VC more diverse.",
      url: "https://techcrunch.com/2023/09/24/equitable-cap-table-tools/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-24T15:00:23+00:00",
    },
    {
      author: "Sheena Vasani",
      title: "LG’s monstrous Gram 17 is nearly half off just for today",
      description:
        "LG’s last-gen Gram 17 offers a spacious screen without sacrificing portability. | Photo by Amelia Holowaty Krales / The Verge Laptops are useful for many things, but your typical 13-inch screen just isn’t spacious enough for hardcore multitaskers. If you want more screen real estate at a reasonable price, Apple’s 15-inch MacBook Air is an obvious choice, as is LG’s Gram 17 when you can find it at a steep discount. Thankfully, last year’s version of the latter is currently on sale at Best Buy with 16GB of RAM, 1TB of storage, and a 12th Gen Core i7-1260P processor for $999.99 ($800 off...",
      url: "https://www.theverge.com/2023/9/20/23880389/lg-gram-17-disney-plus-apple-ipad-pro-homepod-deal-sale",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T12:52:59+00:00",
    },
    {
      author: "Daniel Cooper",
      title:
        "Blink's new Outdoor 4 camera accessories include battery and range extenders",
      description:
        "It’s been less than a month since Blink, Amazon’s other security camera company, released the Outdoor 4. Now, as part of Amazon’s big September product showcase, we’re getting a trio of accessories to help the camera travel further and do more when it gets there.First on the list is the Sync Module Pro, which lets you place your Outdoor 4 further from your home’s wireless network. The company says you can install a camera in “the furthest corner of your property” without worrying about range, but hasn’t yet shared real-world measurements. Maybe those figures haven’t been...",
      url: "https://www.engadget.com/blinks-new-outdoor-4-camera-accessories-include-battery-and-range-extenders-160101967.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/f3d5dd80-579f-11ee-b3fd-1d7aa3f58b9e",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T16:01:01+00:00",
    },
    {
      author: "Haje Jan Kamps",
      title: "Don’t use builds, reveals or animations in your pitch deck",
      description:
        "In a world of ever-advancing technologies, it can be tempting to embed your pitch deck with all the latest bells and whistles. But do they even work?",
      url: "https://techcrunch.com/2023/09/20/dont-use-builds-reveals-or-animations-in-your-pitch-deck/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T16:00:40+00:00",
    },
    {
      author: null,
      title:
        "BuildZoom (better way to build custom homes) Is hiring a Growth Associate",
      description: "Comments",
      url: "https://jobs.lever.co/buildzoom",
      source: "Hacker News",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T21:02:37+00:00",
    },
    {
      author: "Tom Warren",
      title: "Microsoft’s Surface and AI event: all the news and announcements",
      description:
        "Photo by Amelia Holowaty Krales / The Verge Microsoft’s big Windows and Surface event will focus on its AI vision of the future. Continue reading&hellip;",
      url: "https://www.theverge.com/2023/9/21/23882273/microsoft-event-surface-windows-office-ai",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T13:15:52+00:00",
    },
    {
      author: "Jay Peters",
      title: "YouTube made a video editing app — just like TikTok",
      description:
        "Illustration by Alex Castro / The Verge YouTube is releasing a new app called YouTube Create that lets you edit video right on your phone, the company announced on Thursday. The new app could encourage more people to make Shorts, YouTube’s take on TikTok-style videos; it’s generally easier to make a TikTok video than it is to make a full-fledged YouTube video, which is a key reason why TikTok has exploded in popularity.Making a separate app also mimics TikTok’s strategy of releasing the separate (and popular) CapCut app, which helps you make videos you can share on TikTok and other...",
      url: "https://www.theverge.com/2023/9/21/23883755/youtube-create-mobile-video-editing-app-tiktok-capcut",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T14:30:00+00:00",
    },
    {
      author: "Mia Sato",
      title: "YouTube is going all in on AI",
      description:
        "Image: YouTube More content on YouTube is going to be created at least in part using generative AI.The video platform announced several new AI-powered tools for creators at its annual Made on YouTube event on Thursday. Among the features coming later this year or next are AI-generated photo and video backgrounds, AI video topic suggestions, and music search.A new feature called Dream Screen will create AI-generated videos and photos that creators can place in the background of their YouTube Shorts. Initially, creators will be able to type in prompts to generate backgrounds; eventually, YouTube...",
      url: "https://www.theverge.com/2023/9/21/23883749/youtube-generative-ai-dream-screen-creators",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T14:30:00+00:00",
    },
    {
      author: "Christine Hall",
      title:
        "eStreamly blends physical, digital shopping with the video as the star",
      description:
        "eStreamly offers business-to-business video commerce software to enable livestreams and videos to be shoppable across platforms.",
      url: "https://techcrunch.com/2023/09/21/estreamly-livestream-shopping-battlefield/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T21:53:50+00:00",
    },
    {
      author: null,
      title: "Microsoft's new Call of Duty deal set for approval",
      description:
        'The revised offer "opens the door" to the deal being cleared, the UK competition watchdog says.',
      url: "https://www.bbc.co.uk/news/business-66875075?at_medium=RSS&at_campaign=KARANGA",
      source: "BBC News - Technology",
      image: null,
      category: "technology",
      language: "en",
      country: "gb",
      published_at: "2023-09-22T07:43:22+00:00",
    },
    {
      author: "Carrie Andrews",
      title: "How CFOs can reduce SaaS spend by 30% in these tough times",
      description:
        "Software spending is now the third-biggest expense for organizations, right after employee and office costs.",
      url: "https://techcrunch.com/2023/09/22/how-cfos-can-reduce-saas-spend-by-30-in-these-tough-times/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-22T22:51:23+00:00",
    },
    {
      author: "Cherlynn Low",
      title:
        "Amazon debuts Eye Gaze accessibility features on the Fire Max 11 tablet",
      description:
        "After spending a chunk of its event today talking about Alexa upgrades, Amazon announced two new accessibility features coming to its devices later this year. First is Eye Gaze on Alexa, which will let those with mobility or speech disabilities use their gaze to perform a set of preset actions on the Fire Max 11 tablet.This is a developing story. Please check back for updates.Follow all of the news live from Amazon’s 2023 Devices event right here.This article originally appeared on Engadget at https://www.engadget.com/amazon-debuts-eye-gaze-accessibility-features-on-the-fire-max-11-tablet-...",
      url: "https://www.engadget.com/amazon-debuts-eye-gaze-accessibility-features-on-the-fire-max-11-tablet-154042714.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/d6fa4e90-57cb-11ee-bfcf-dae5c9cdc738",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T15:40:42+00:00",
    },
    {
      author: "Aria Alamalhodaei",
      title:
        "Navigating public-private partnerships with Uber, Cruise, and the Mayor of Atlanta",
      description:
        "Tech companies say they will help cities reach their ambitious decarbonization goals, but increasing public trust and working closely with government partners is key, panelists said during a roundtable on sustainability in cities at TechCrunch Disrupt 2023. These issues were thrown into sharp relief for the city of Atlanta a few years ago, when electric [&#8230;]",
      url: "https://techcrunch.com/2023/09/20/navigating-public-private-partnerships-with-uber-cruise-and-the-mayor-of-atlanta/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T19:50:29+00:00",
    },
    {
      author: "Brian Heater",
      title:
        "Reekon hopes high-tech home improvement tools can drag contractors into the 21st century",
      description:
        "TechCrunch Disrupt Battlefield company Reekon is building the next generation of smart tools for home contractors.",
      url: "https://techcrunch.com/2023/09/20/reekon-hopes-high-tech-home-improvement-tools-can-drag-contractors-into-the-21st-century/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T20:34:50+00:00",
    },
    {
      author: "Emma Roth",
      title:
        "Here are the details on the grisly deaths of Elon Musk’s Neuralink monkeys",
      description:
        "Illustration by Lille Allen / The Verge Elon Musk said earlier this month that “no monkey has died as a result of a Neuralink implant,” but an alarming new report from Wired seems to contradict Musk’s statement. Public documents obtained by the Physicians Committee for Responsible Medicine (PCRM) and seen by Wired indicate that Neuralink’s macaque subjects were euthanized after suffering various complications, including “bloody diarrhea, partial paralysis, and cerebral edema.”Wired writes that the documents show a male monkey was euthanized in March 2020 “after his cranial implant...",
      url: "https://www.theverge.com/2023/9/20/23882888/elon-musk-brain-implant-startup-neuralink-monkeys-euthanized",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-20T22:56:31+00:00",
    },
    {
      author: "Natasha Lomas",
      title: "Poland opens privacy probe of ChatGPT following GDPR complaint",
      description:
        "OpenAI is facing another investigation into whether its generative AI chatbot, ChatGPT, complies with European Union privacy laws. Last month a complaint was filed against ChatGPT and OpenAI in Poland, accusing the company of a string of breaches of the EU&#8217;s General Data Protection Regulation (GDPR). Yesterday the Polish authority took the unusual step of [&#8230;]",
      url: "https://techcrunch.com/2023/09/21/poland-chatgpt-gdpr-complaint-probe/",
      source: "TechCrunch",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T11:26:57+00:00",
    },
    {
      author: "Emma Roth",
      title: "Microsoft Surface event: the 6 biggest announcements",
      description:
        "Photo by Chris Welch / The Verge Microsoft has just wrapped up its September event, where it made several major announcements. Not only did we see some new Surface devices, but Microsoft also shared some updates about the new AI features coming to its products.You can check out all the news from Microsoft’s event below.A more powerful Surface Laptop Studio 2 Image: Microsoft Microsoft has finally revealed its new Surface Laptop Studio 2. The company calls it the “most powerful” Surface it has built to date, as it comes with Intel’s 13th Gen i7 H class processor, Nvidia’s RTX 4050 or...",
      url: "https://www.theverge.com/2023/9/21/23882074/microsoft-surface-copilot-event-2023-biggest-announcements",
      source: "The Verge",
      image: null,
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T15:24:23+00:00",
    },
    {
      author: "Engadget",
      title: "The best Xbox games for 2023",
      description:
        "A series of missteps put Microsoft in second place before the Xbox One even came out. With the launch of the Xbox Series X and S, though, Microsoft is in a great position to compete. Both are well-priced, well-specced consoles with a huge library of games spanning two decades.Microsoft’s console strategy is unique. Someone with a 7-year old Xbox One has access to an almost-identical library of games as the owner of a brand-new Xbox Series X. That makes it difficult to maintain meaningfully different lists for its various consoles — at least for now. But while next-gen exclusives may be few...",
      url: "https://www.engadget.com/best-xbox-games-140022399.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2020-11/1a78db70-1d1c-11eb-8f7e-21a8e3cff5ce",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T16:30:55+00:00",
    },
    {
      author: "Sarah Fielding",
      title:
        "Hyundai is offering a free EV charger and $600 off installation for a limited time",
      description:
        "While the better environmental impact and lack of gas payments make EVs an enticing option, other costs and steps still stand as a hindrance. Hyundai is the latest car manufacturer attempting to minimize these negatives with a new incentive offering complimentary chargers and up to $600 off their installation fee. Hyundai&#39;s ChargePoint Home Flex Level 2 EV Charger is typically $549, providing a $1,100 total savings.The offer is available for anyone leasing or purchasing a brand new 2023 or 2024 Ioniq 5 or Ioniq 6 and a 2023 Kona Electric. However, it has to be through Hyundai Motor Finance...",
      url: "https://www.engadget.com/hyundai-is-offering-a-free-ev-charger-and-600-off-installation-for-a-limited-time-170057694.html?src=rss",
      source: "Engadget",
      image:
        "https://s.yimg.com/os/creatr-uploaded-images/2023-09/c1537d40-587b-11ee-9fef-3020b0839b68",
      category: "technology",
      language: "en",
      country: "us",
      published_at: "2023-09-21T17:00:57+00:00",
    },
  ],
};
